//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for BenefitsLifeEventOptionSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("BenefitsLifeEventOptionSingle")]
    public partial class BenefitsLifeEventOptionSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<BenefitsLifeEventOption>
    {
        /// <summary>
        /// Initialize a new BenefitsLifeEventOptionSingle object.
        /// </summary>
        public BenefitsLifeEventOptionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new BenefitsLifeEventOptionSingle object.
        /// </summary>
        public BenefitsLifeEventOptionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new BenefitsLifeEventOptionSingle object.
        /// </summary>
        public BenefitsLifeEventOptionSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<BenefitsLifeEventOption> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for BenefitsLifeEventType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BenefitsLifeEventType")]
        public virtual global::Microsoft.Dynamics.DataEntities.BenefitsLifeEventTypeSingle BenefitsLifeEventType
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._BenefitsLifeEventType == null))
                {
                    this._BenefitsLifeEventType = new global::Microsoft.Dynamics.DataEntities.BenefitsLifeEventTypeSingle(this.Context, GetPath("BenefitsLifeEventType"));
                }
                return this._BenefitsLifeEventType;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.BenefitsLifeEventTypeSingle _BenefitsLifeEventType;
        /// <summary>
        /// There are no comments for BenefitsPlanType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BenefitsPlanType")]
        public virtual global::Microsoft.Dynamics.DataEntities.BenefitsPlanTypeSingle BenefitsPlanType
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._BenefitsPlanType == null))
                {
                    this._BenefitsPlanType = new global::Microsoft.Dynamics.DataEntities.BenefitsPlanTypeSingle(this.Context, GetPath("BenefitsPlanType"));
                }
                return this._BenefitsPlanType;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.BenefitsPlanTypeSingle _BenefitsPlanType;
    }
    /// <summary>
    /// There are no comments for BenefitsLifeEventOption in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PlanTypeId
    /// LifeEventTypeId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("PlanTypeId", "LifeEventTypeId")]
    [global::Microsoft.OData.Client.EntitySet("BenefitsLifeEventOptions")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("BenefitsLifeEventOption")]
    public partial class BenefitsLifeEventOption : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new BenefitsLifeEventOption object.
        /// </summary>
        /// <param name="planTypeId">Initial value of PlanTypeId.</param>
        /// <param name="lifeEventTypeId">Initial value of LifeEventTypeId.</param>
        /// <param name="lifeEventReportingWindow">Initial value of LifeEventReportingWindow.</param>
        /// <param name="benefitsLifeEventType">Initial value of BenefitsLifeEventType.</param>
        /// <param name="benefitsPlanType">Initial value of BenefitsPlanType.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static BenefitsLifeEventOption CreateBenefitsLifeEventOption(string planTypeId, string lifeEventTypeId, int lifeEventReportingWindow, global::Microsoft.Dynamics.DataEntities.BenefitsLifeEventType benefitsLifeEventType, global::Microsoft.Dynamics.DataEntities.BenefitsPlanType benefitsPlanType)
        {
            BenefitsLifeEventOption benefitsLifeEventOption = new BenefitsLifeEventOption();
            benefitsLifeEventOption.PlanTypeId = planTypeId;
            benefitsLifeEventOption.LifeEventTypeId = lifeEventTypeId;
            benefitsLifeEventOption.LifeEventReportingWindow = lifeEventReportingWindow;
            if ((benefitsLifeEventType == null))
            {
                throw new global::System.ArgumentNullException("benefitsLifeEventType");
            }
            benefitsLifeEventOption.BenefitsLifeEventType = benefitsLifeEventType;
            if ((benefitsPlanType == null))
            {
                throw new global::System.ArgumentNullException("benefitsPlanType");
            }
            benefitsLifeEventOption.BenefitsPlanType = benefitsPlanType;
            return benefitsLifeEventOption;
        }
        /// <summary>
        /// There are no comments for Property PlanTypeId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PlanTypeId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "PlanTypeId is required.")]
        public virtual string PlanTypeId
        {
            get
            {
                return this._PlanTypeId;
            }
            set
            {
                this.OnPlanTypeIdChanging(value);
                this._PlanTypeId = value;
                this.OnPlanTypeIdChanged();
                this.OnPropertyChanged("PlanTypeId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PlanTypeId;
        partial void OnPlanTypeIdChanging(string value);
        partial void OnPlanTypeIdChanged();
        /// <summary>
        /// There are no comments for Property LifeEventTypeId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LifeEventTypeId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "LifeEventTypeId is required.")]
        public virtual string LifeEventTypeId
        {
            get
            {
                return this._LifeEventTypeId;
            }
            set
            {
                this.OnLifeEventTypeIdChanging(value);
                this._LifeEventTypeId = value;
                this.OnLifeEventTypeIdChanged();
                this.OnPropertyChanged("LifeEventTypeId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _LifeEventTypeId;
        partial void OnLifeEventTypeIdChanging(string value);
        partial void OnLifeEventTypeIdChanged();
        /// <summary>
        /// There are no comments for Property OpenFlexCreditsAllocation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("OpenFlexCreditsAllocation")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> OpenFlexCreditsAllocation
        {
            get
            {
                return this._OpenFlexCreditsAllocation;
            }
            set
            {
                this.OnOpenFlexCreditsAllocationChanging(value);
                this._OpenFlexCreditsAllocation = value;
                this.OnOpenFlexCreditsAllocationChanged();
                this.OnPropertyChanged("OpenFlexCreditsAllocation");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _OpenFlexCreditsAllocation;
        partial void OnOpenFlexCreditsAllocationChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnOpenFlexCreditsAllocationChanged();
        /// <summary>
        /// There are no comments for Property ChangeCoverageOption in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ChangeCoverageOption")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> ChangeCoverageOption
        {
            get
            {
                return this._ChangeCoverageOption;
            }
            set
            {
                this.OnChangeCoverageOptionChanging(value);
                this._ChangeCoverageOption = value;
                this.OnChangeCoverageOptionChanged();
                this.OnPropertyChanged("ChangeCoverageOption");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _ChangeCoverageOption;
        partial void OnChangeCoverageOptionChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnChangeCoverageOptionChanged();
        /// <summary>
        /// There are no comments for Property AutoReOpenEligibilityCheck in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AutoReOpenEligibilityCheck")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> AutoReOpenEligibilityCheck
        {
            get
            {
                return this._AutoReOpenEligibilityCheck;
            }
            set
            {
                this.OnAutoReOpenEligibilityCheckChanging(value);
                this._AutoReOpenEligibilityCheck = value;
                this.OnAutoReOpenEligibilityCheckChanged();
                this.OnPropertyChanged("AutoReOpenEligibilityCheck");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _AutoReOpenEligibilityCheck;
        partial void OnAutoReOpenEligibilityCheckChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnAutoReOpenEligibilityCheckChanged();
        /// <summary>
        /// There are no comments for Property PreventRemovingFlexCreditsFromAllocation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PreventRemovingFlexCreditsFromAllocation")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> PreventRemovingFlexCreditsFromAllocation
        {
            get
            {
                return this._PreventRemovingFlexCreditsFromAllocation;
            }
            set
            {
                this.OnPreventRemovingFlexCreditsFromAllocationChanging(value);
                this._PreventRemovingFlexCreditsFromAllocation = value;
                this.OnPreventRemovingFlexCreditsFromAllocationChanged();
                this.OnPropertyChanged("PreventRemovingFlexCreditsFromAllocation");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _PreventRemovingFlexCreditsFromAllocation;
        partial void OnPreventRemovingFlexCreditsFromAllocationChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnPreventRemovingFlexCreditsFromAllocationChanged();
        /// <summary>
        /// There are no comments for Property PreventAdditionsToFlexCreditsAllocation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PreventAdditionsToFlexCreditsAllocation")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> PreventAdditionsToFlexCreditsAllocation
        {
            get
            {
                return this._PreventAdditionsToFlexCreditsAllocation;
            }
            set
            {
                this.OnPreventAdditionsToFlexCreditsAllocationChanging(value);
                this._PreventAdditionsToFlexCreditsAllocation = value;
                this.OnPreventAdditionsToFlexCreditsAllocationChanged();
                this.OnPropertyChanged("PreventAdditionsToFlexCreditsAllocation");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _PreventAdditionsToFlexCreditsAllocation;
        partial void OnPreventAdditionsToFlexCreditsAllocationChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnPreventAdditionsToFlexCreditsAllocationChanged();
        /// <summary>
        /// There are no comments for Property AllowCancellation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AllowCancellation")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> AllowCancellation
        {
            get
            {
                return this._AllowCancellation;
            }
            set
            {
                this.OnAllowCancellationChanging(value);
                this._AllowCancellation = value;
                this.OnAllowCancellationChanged();
                this.OnPropertyChanged("AllowCancellation");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _AllowCancellation;
        partial void OnAllowCancellationChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnAllowCancellationChanged();
        /// <summary>
        /// There are no comments for Property ChangeToNewPlan in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ChangeToNewPlan")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> ChangeToNewPlan
        {
            get
            {
                return this._ChangeToNewPlan;
            }
            set
            {
                this.OnChangeToNewPlanChanging(value);
                this._ChangeToNewPlan = value;
                this.OnChangeToNewPlanChanged();
                this.OnPropertyChanged("ChangeToNewPlan");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _ChangeToNewPlan;
        partial void OnChangeToNewPlanChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnChangeToNewPlanChanged();
        /// <summary>
        /// There are no comments for Property LifeEventReportingWindow in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LifeEventReportingWindow")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "LifeEventReportingWindow is required.")]
        public virtual int LifeEventReportingWindow
        {
            get
            {
                return this._LifeEventReportingWindow;
            }
            set
            {
                this.OnLifeEventReportingWindowChanging(value);
                this._LifeEventReportingWindow = value;
                this.OnLifeEventReportingWindowChanged();
                this.OnPropertyChanged("LifeEventReportingWindow");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _LifeEventReportingWindow;
        partial void OnLifeEventReportingWindowChanging(int value);
        partial void OnLifeEventReportingWindowChanged();
        /// <summary>
        /// There are no comments for Property AutoCancelPlan in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AutoCancelPlan")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> AutoCancelPlan
        {
            get
            {
                return this._AutoCancelPlan;
            }
            set
            {
                this.OnAutoCancelPlanChanging(value);
                this._AutoCancelPlan = value;
                this.OnAutoCancelPlanChanged();
                this.OnPropertyChanged("AutoCancelPlan");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _AutoCancelPlan;
        partial void OnAutoCancelPlanChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnAutoCancelPlanChanged();
        /// <summary>
        /// There are no comments for Property BenefitsLifeEventType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BenefitsLifeEventType")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "BenefitsLifeEventType is required.")]
        public virtual global::Microsoft.Dynamics.DataEntities.BenefitsLifeEventType BenefitsLifeEventType
        {
            get
            {
                return this._BenefitsLifeEventType;
            }
            set
            {
                this.OnBenefitsLifeEventTypeChanging(value);
                this._BenefitsLifeEventType = value;
                this.OnBenefitsLifeEventTypeChanged();
                this.OnPropertyChanged("BenefitsLifeEventType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.BenefitsLifeEventType _BenefitsLifeEventType;
        partial void OnBenefitsLifeEventTypeChanging(global::Microsoft.Dynamics.DataEntities.BenefitsLifeEventType value);
        partial void OnBenefitsLifeEventTypeChanged();
        /// <summary>
        /// There are no comments for Property BenefitsPlanType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BenefitsPlanType")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "BenefitsPlanType is required.")]
        public virtual global::Microsoft.Dynamics.DataEntities.BenefitsPlanType BenefitsPlanType
        {
            get
            {
                return this._BenefitsPlanType;
            }
            set
            {
                this.OnBenefitsPlanTypeChanging(value);
                this._BenefitsPlanType = value;
                this.OnBenefitsPlanTypeChanged();
                this.OnPropertyChanged("BenefitsPlanType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.BenefitsPlanType _BenefitsPlanType;
        partial void OnBenefitsPlanTypeChanging(global::Microsoft.Dynamics.DataEntities.BenefitsPlanType value);
        partial void OnBenefitsPlanTypeChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
