//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for CallCenterCustomerCouponSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CallCenterCustomerCouponSingle")]
    public partial class CallCenterCustomerCouponSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<CallCenterCustomerCoupon>
    {
        /// <summary>
        /// Initialize a new CallCenterCustomerCouponSingle object.
        /// </summary>
        public CallCenterCustomerCouponSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CallCenterCustomerCouponSingle object.
        /// </summary>
        public CallCenterCustomerCouponSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CallCenterCustomerCouponSingle object.
        /// </summary>
        public CallCenterCustomerCouponSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<CallCenterCustomerCoupon> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for CallCenterCustomerCoupon in the schema.
    /// </summary>
    /// <KeyProperties>
    /// DataAreaId
    /// CustomerAccountNumber
    /// CustomerGroupId
    /// CouponId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("dataAreaId", "CustomerAccountNumber", "CustomerGroupId", "CouponId")]
    [global::Microsoft.OData.Client.EntitySet("CallCenterCustomerCoupons")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("CallCenterCustomerCoupon")]
    public partial class CallCenterCustomerCoupon : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CallCenterCustomerCoupon object.
        /// </summary>
        /// <param name="dataAreaId">Initial value of DataAreaId.</param>
        /// <param name="customerAccountNumber">Initial value of CustomerAccountNumber.</param>
        /// <param name="customerGroupId">Initial value of CustomerGroupId.</param>
        /// <param name="couponId">Initial value of CouponId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static CallCenterCustomerCoupon CreateCallCenterCustomerCoupon(string dataAreaId, string customerAccountNumber, string customerGroupId, string couponId)
        {
            CallCenterCustomerCoupon callCenterCustomerCoupon = new CallCenterCustomerCoupon();
            callCenterCustomerCoupon.DataAreaId = dataAreaId;
            callCenterCustomerCoupon.CustomerAccountNumber = customerAccountNumber;
            callCenterCustomerCoupon.CustomerGroupId = customerGroupId;
            callCenterCustomerCoupon.CouponId = couponId;
            return callCenterCustomerCoupon;
        }
        /// <summary>
        /// There are no comments for Property DataAreaId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("dataAreaId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "DataAreaId is required.")]
        public virtual string DataAreaId
        {
            get
            {
                return this._DataAreaId;
            }
            set
            {
                this.OnDataAreaIdChanging(value);
                this._DataAreaId = value;
                this.OnDataAreaIdChanged();
                this.OnPropertyChanged("dataAreaId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DataAreaId;
        partial void OnDataAreaIdChanging(string value);
        partial void OnDataAreaIdChanged();
        /// <summary>
        /// There are no comments for Property CustomerAccountNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CustomerAccountNumber")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "CustomerAccountNumber is required.")]
        public virtual string CustomerAccountNumber
        {
            get
            {
                return this._CustomerAccountNumber;
            }
            set
            {
                this.OnCustomerAccountNumberChanging(value);
                this._CustomerAccountNumber = value;
                this.OnCustomerAccountNumberChanged();
                this.OnPropertyChanged("CustomerAccountNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _CustomerAccountNumber;
        partial void OnCustomerAccountNumberChanging(string value);
        partial void OnCustomerAccountNumberChanged();
        /// <summary>
        /// There are no comments for Property CustomerGroupId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CustomerGroupId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "CustomerGroupId is required.")]
        public virtual string CustomerGroupId
        {
            get
            {
                return this._CustomerGroupId;
            }
            set
            {
                this.OnCustomerGroupIdChanging(value);
                this._CustomerGroupId = value;
                this.OnCustomerGroupIdChanged();
                this.OnPropertyChanged("CustomerGroupId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _CustomerGroupId;
        partial void OnCustomerGroupIdChanging(string value);
        partial void OnCustomerGroupIdChanged();
        /// <summary>
        /// There are no comments for Property CouponId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CouponId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "CouponId is required.")]
        public virtual string CouponId
        {
            get
            {
                return this._CouponId;
            }
            set
            {
                this.OnCouponIdChanging(value);
                this._CouponId = value;
                this.OnCouponIdChanged();
                this.OnPropertyChanged("CouponId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _CouponId;
        partial void OnCouponIdChanging(string value);
        partial void OnCouponIdChanged();
        /// <summary>
        /// There are no comments for Property IsCouponVoided in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("IsCouponVoided")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> IsCouponVoided
        {
            get
            {
                return this._IsCouponVoided;
            }
            set
            {
                this.OnIsCouponVoidedChanging(value);
                this._IsCouponVoided = value;
                this.OnIsCouponVoidedChanged();
                this.OnPropertyChanged("IsCouponVoided");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _IsCouponVoided;
        partial void OnIsCouponVoidedChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnIsCouponVoidedChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
