//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for CardTypesSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CardTypesSingle")]
    public partial class CardTypesSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<CardTypes>
    {
        /// <summary>
        /// Initialize a new CardTypesSingle object.
        /// </summary>
        public CardTypesSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CardTypesSingle object.
        /// </summary>
        public CardTypesSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CardTypesSingle object.
        /// </summary>
        public CardTypesSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<CardTypes> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for CardTypes in the schema.
    /// </summary>
    /// <KeyProperties>
    /// DataAreaId
    /// TrvCreditCardType
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("dataAreaId", "TrvCreditCardType")]
    [global::Microsoft.OData.Client.EntitySet("CardTypes")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("CardTypes")]
    public partial class CardTypes : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CardTypes object.
        /// </summary>
        /// <param name="dataAreaId">Initial value of DataAreaId.</param>
        /// <param name="trvCreditCardType">Initial value of TrvCreditCardType.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static CardTypes CreateCardTypes(string dataAreaId, string trvCreditCardType)
        {
            CardTypes cardTypes = new CardTypes();
            cardTypes.DataAreaId = dataAreaId;
            cardTypes.TrvCreditCardType = trvCreditCardType;
            return cardTypes;
        }
        /// <summary>
        /// There are no comments for Property DataAreaId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("dataAreaId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "DataAreaId is required.")]
        public virtual string DataAreaId
        {
            get
            {
                return this._DataAreaId;
            }
            set
            {
                this.OnDataAreaIdChanging(value);
                this._DataAreaId = value;
                this.OnDataAreaIdChanged();
                this.OnPropertyChanged("dataAreaId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DataAreaId;
        partial void OnDataAreaIdChanging(string value);
        partial void OnDataAreaIdChanged();
        /// <summary>
        /// There are no comments for Property TrvCreditCardType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TrvCreditCardType")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "TrvCreditCardType is required.")]
        public virtual string TrvCreditCardType
        {
            get
            {
                return this._TrvCreditCardType;
            }
            set
            {
                this.OnTrvCreditCardTypeChanging(value);
                this._TrvCreditCardType = value;
                this.OnTrvCreditCardTypeChanged();
                this.OnPropertyChanged("TrvCreditCardType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TrvCreditCardType;
        partial void OnTrvCreditCardTypeChanging(string value);
        partial void OnTrvCreditCardTypeChanged();
        /// <summary>
        /// There are no comments for Property TrvCreditCardDesc in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TrvCreditCardDesc")]
        public virtual string TrvCreditCardDesc
        {
            get
            {
                return this._TrvCreditCardDesc;
            }
            set
            {
                this.OnTrvCreditCardDescChanging(value);
                this._TrvCreditCardDesc = value;
                this.OnTrvCreditCardDescChanged();
                this.OnPropertyChanged("TrvCreditCardDesc");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TrvCreditCardDesc;
        partial void OnTrvCreditCardDescChanging(string value);
        partial void OnTrvCreditCardDescChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
