//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for CaseCategoryTypeSecuritySingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CaseCategoryTypeSecuritySingle")]
    public partial class CaseCategoryTypeSecuritySingle : global::Microsoft.OData.Client.DataServiceQuerySingle<CaseCategoryTypeSecurity>
    {
        /// <summary>
        /// Initialize a new CaseCategoryTypeSecuritySingle object.
        /// </summary>
        public CaseCategoryTypeSecuritySingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CaseCategoryTypeSecuritySingle object.
        /// </summary>
        public CaseCategoryTypeSecuritySingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CaseCategoryTypeSecuritySingle object.
        /// </summary>
        public CaseCategoryTypeSecuritySingle(global::Microsoft.OData.Client.DataServiceQuerySingle<CaseCategoryTypeSecurity> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for CaseCategoryTypeSecurity in the schema.
    /// </summary>
    /// <KeyProperties>
    /// DataAreaId
    /// SecurityRole
    /// CaseCategoryType
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("dataAreaId", "SecurityRole", "CaseCategoryType")]
    [global::Microsoft.OData.Client.EntitySet("CaseCategoryTypeSecurities")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("CaseCategoryTypeSecurity")]
    public partial class CaseCategoryTypeSecurity : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CaseCategoryTypeSecurity object.
        /// </summary>
        /// <param name="dataAreaId">Initial value of DataAreaId.</param>
        /// <param name="securityRole">Initial value of SecurityRole.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static CaseCategoryTypeSecurity CreateCaseCategoryTypeSecurity(string dataAreaId, string securityRole)
        {
            CaseCategoryTypeSecurity caseCategoryTypeSecurity = new CaseCategoryTypeSecurity();
            caseCategoryTypeSecurity.DataAreaId = dataAreaId;
            caseCategoryTypeSecurity.SecurityRole = securityRole;
            return caseCategoryTypeSecurity;
        }
        /// <summary>
        /// There are no comments for Property DataAreaId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("dataAreaId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "DataAreaId is required.")]
        public virtual string DataAreaId
        {
            get
            {
                return this._DataAreaId;
            }
            set
            {
                this.OnDataAreaIdChanging(value);
                this._DataAreaId = value;
                this.OnDataAreaIdChanged();
                this.OnPropertyChanged("dataAreaId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DataAreaId;
        partial void OnDataAreaIdChanging(string value);
        partial void OnDataAreaIdChanged();
        /// <summary>
        /// There are no comments for Property SecurityRole in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SecurityRole")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "SecurityRole is required.")]
        public virtual string SecurityRole
        {
            get
            {
                return this._SecurityRole;
            }
            set
            {
                this.OnSecurityRoleChanging(value);
                this._SecurityRole = value;
                this.OnSecurityRoleChanged();
                this.OnPropertyChanged("SecurityRole");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SecurityRole;
        partial void OnSecurityRoleChanging(string value);
        partial void OnSecurityRoleChanged();
        /// <summary>
        /// There are no comments for Property CaseCategoryType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CaseCategoryType")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.CaseCategoryType> CaseCategoryType
        {
            get
            {
                return this._CaseCategoryType;
            }
            set
            {
                this.OnCaseCategoryTypeChanging(value);
                this._CaseCategoryType = value;
                this.OnCaseCategoryTypeChanged();
                this.OnPropertyChanged("CaseCategoryType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.CaseCategoryType> _CaseCategoryType;
        partial void OnCaseCategoryTypeChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.CaseCategoryType> value);
        partial void OnCaseCategoryTypeChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
