//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for CostAccountingDataConnectorBudgetEntrySingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CostAccountingDataConnectorBudgetEntrySingle")]
    public partial class CostAccountingDataConnectorBudgetEntrySingle : global::Microsoft.OData.Client.DataServiceQuerySingle<CostAccountingDataConnectorBudgetEntry>
    {
        /// <summary>
        /// Initialize a new CostAccountingDataConnectorBudgetEntrySingle object.
        /// </summary>
        public CostAccountingDataConnectorBudgetEntrySingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CostAccountingDataConnectorBudgetEntrySingle object.
        /// </summary>
        public CostAccountingDataConnectorBudgetEntrySingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CostAccountingDataConnectorBudgetEntrySingle object.
        /// </summary>
        public CostAccountingDataConnectorBudgetEntrySingle(global::Microsoft.OData.Client.DataServiceQuerySingle<CostAccountingDataConnectorBudgetEntry> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for CostAccountingDataConnectorBudgetEntry in the schema.
    /// </summary>
    /// <KeyProperties>
    /// DataConnectorSystemInstanceSurrogateKey
    /// SourceIdentifier
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("DataConnectorSystemInstanceSurrogateKey", "SourceIdentifier")]
    [global::Microsoft.OData.Client.EntitySet("CostAccountingDataConnectorBudgetEntries")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("CostAccountingDataConnectorBudgetEntry")]
    public partial class CostAccountingDataConnectorBudgetEntry : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CostAccountingDataConnectorBudgetEntry object.
        /// </summary>
        /// <param name="dataConnectorSystemInstanceSurrogateKey">Initial value of DataConnectorSystemInstanceSurrogateKey.</param>
        /// <param name="sourceIdentifier">Initial value of SourceIdentifier.</param>
        /// <param name="accountingDate">Initial value of AccountingDate.</param>
        /// <param name="amount">Initial value of Amount.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static CostAccountingDataConnectorBudgetEntry CreateCostAccountingDataConnectorBudgetEntry(string dataConnectorSystemInstanceSurrogateKey, string sourceIdentifier, global::System.DateTimeOffset accountingDate, decimal amount)
        {
            CostAccountingDataConnectorBudgetEntry costAccountingDataConnectorBudgetEntry = new CostAccountingDataConnectorBudgetEntry();
            costAccountingDataConnectorBudgetEntry.DataConnectorSystemInstanceSurrogateKey = dataConnectorSystemInstanceSurrogateKey;
            costAccountingDataConnectorBudgetEntry.SourceIdentifier = sourceIdentifier;
            costAccountingDataConnectorBudgetEntry.AccountingDate = accountingDate;
            costAccountingDataConnectorBudgetEntry.Amount = amount;
            return costAccountingDataConnectorBudgetEntry;
        }
        /// <summary>
        /// There are no comments for Property DataConnectorSystemInstanceSurrogateKey in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DataConnectorSystemInstanceSurrogateKey")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "DataConnectorSystemInstanceSurrogateKey is required.")]
        public virtual string DataConnectorSystemInstanceSurrogateKey
        {
            get
            {
                return this._DataConnectorSystemInstanceSurrogateKey;
            }
            set
            {
                this.OnDataConnectorSystemInstanceSurrogateKeyChanging(value);
                this._DataConnectorSystemInstanceSurrogateKey = value;
                this.OnDataConnectorSystemInstanceSurrogateKeyChanged();
                this.OnPropertyChanged("DataConnectorSystemInstanceSurrogateKey");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DataConnectorSystemInstanceSurrogateKey;
        partial void OnDataConnectorSystemInstanceSurrogateKeyChanging(string value);
        partial void OnDataConnectorSystemInstanceSurrogateKeyChanged();
        /// <summary>
        /// There are no comments for Property SourceIdentifier in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SourceIdentifier")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "SourceIdentifier is required.")]
        public virtual string SourceIdentifier
        {
            get
            {
                return this._SourceIdentifier;
            }
            set
            {
                this.OnSourceIdentifierChanging(value);
                this._SourceIdentifier = value;
                this.OnSourceIdentifierChanged();
                this.OnPropertyChanged("SourceIdentifier");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SourceIdentifier;
        partial void OnSourceIdentifierChanging(string value);
        partial void OnSourceIdentifierChanged();
        /// <summary>
        /// There are no comments for Property DataConnectorLegalEntityName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DataConnectorLegalEntityName")]
        public virtual string DataConnectorLegalEntityName
        {
            get
            {
                return this._DataConnectorLegalEntityName;
            }
            set
            {
                this.OnDataConnectorLegalEntityNameChanging(value);
                this._DataConnectorLegalEntityName = value;
                this.OnDataConnectorLegalEntityNameChanged();
                this.OnPropertyChanged("DataConnectorLegalEntityName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DataConnectorLegalEntityName;
        partial void OnDataConnectorLegalEntityNameChanging(string value);
        partial void OnDataConnectorLegalEntityNameChanged();
        /// <summary>
        /// There are no comments for Property DataConnectorBudgetModelName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DataConnectorBudgetModelName")]
        public virtual string DataConnectorBudgetModelName
        {
            get
            {
                return this._DataConnectorBudgetModelName;
            }
            set
            {
                this.OnDataConnectorBudgetModelNameChanging(value);
                this._DataConnectorBudgetModelName = value;
                this.OnDataConnectorBudgetModelNameChanged();
                this.OnPropertyChanged("DataConnectorBudgetModelName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DataConnectorBudgetModelName;
        partial void OnDataConnectorBudgetModelNameChanging(string value);
        partial void OnDataConnectorBudgetModelNameChanged();
        /// <summary>
        /// There are no comments for Property MainAccountName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("MainAccountName")]
        public virtual string MainAccountName
        {
            get
            {
                return this._MainAccountName;
            }
            set
            {
                this.OnMainAccountNameChanging(value);
                this._MainAccountName = value;
                this.OnMainAccountNameChanged();
                this.OnPropertyChanged("MainAccountName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _MainAccountName;
        partial void OnMainAccountNameChanging(string value);
        partial void OnMainAccountNameChanged();
        /// <summary>
        /// There are no comments for Property CurrencyCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CurrencyCode")]
        public virtual string CurrencyCode
        {
            get
            {
                return this._CurrencyCode;
            }
            set
            {
                this.OnCurrencyCodeChanging(value);
                this._CurrencyCode = value;
                this.OnCurrencyCodeChanged();
                this.OnPropertyChanged("CurrencyCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _CurrencyCode;
        partial void OnCurrencyCodeChanging(string value);
        partial void OnCurrencyCodeChanged();
        /// <summary>
        /// There are no comments for Property DataConnectorDataTransferSurrogateKey in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DataConnectorDataTransferSurrogateKey")]
        public virtual string DataConnectorDataTransferSurrogateKey
        {
            get
            {
                return this._DataConnectorDataTransferSurrogateKey;
            }
            set
            {
                this.OnDataConnectorDataTransferSurrogateKeyChanging(value);
                this._DataConnectorDataTransferSurrogateKey = value;
                this.OnDataConnectorDataTransferSurrogateKeyChanged();
                this.OnPropertyChanged("DataConnectorDataTransferSurrogateKey");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DataConnectorDataTransferSurrogateKey;
        partial void OnDataConnectorDataTransferSurrogateKeyChanging(string value);
        partial void OnDataConnectorDataTransferSurrogateKeyChanged();
        /// <summary>
        /// There are no comments for Property DataConnectorBudgetEntryTypeName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DataConnectorBudgetEntryTypeName")]
        public virtual string DataConnectorBudgetEntryTypeName
        {
            get
            {
                return this._DataConnectorBudgetEntryTypeName;
            }
            set
            {
                this.OnDataConnectorBudgetEntryTypeNameChanging(value);
                this._DataConnectorBudgetEntryTypeName = value;
                this.OnDataConnectorBudgetEntryTypeNameChanged();
                this.OnPropertyChanged("DataConnectorBudgetEntryTypeName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DataConnectorBudgetEntryTypeName;
        partial void OnDataConnectorBudgetEntryTypeNameChanging(string value);
        partial void OnDataConnectorBudgetEntryTypeNameChanged();
        /// <summary>
        /// There are no comments for Property DebitCredit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DebitCredit")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.CAMDebitCredit> DebitCredit
        {
            get
            {
                return this._DebitCredit;
            }
            set
            {
                this.OnDebitCreditChanging(value);
                this._DebitCredit = value;
                this.OnDebitCreditChanged();
                this.OnPropertyChanged("DebitCredit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.CAMDebitCredit> _DebitCredit;
        partial void OnDebitCreditChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.CAMDebitCredit> value);
        partial void OnDebitCreditChanged();
        /// <summary>
        /// There are no comments for Property AccountingDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AccountingDate")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "AccountingDate is required.")]
        public virtual global::System.DateTimeOffset AccountingDate
        {
            get
            {
                return this._AccountingDate;
            }
            set
            {
                this.OnAccountingDateChanging(value);
                this._AccountingDate = value;
                this.OnAccountingDateChanged();
                this.OnPropertyChanged("AccountingDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _AccountingDate;
        partial void OnAccountingDateChanging(global::System.DateTimeOffset value);
        partial void OnAccountingDateChanged();
        /// <summary>
        /// There are no comments for Property Amount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Amount")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Amount is required.")]
        public virtual decimal Amount
        {
            get
            {
                return this._Amount;
            }
            set
            {
                this.OnAmountChanging(value);
                this._Amount = value;
                this.OnAmountChanged();
                this.OnPropertyChanged("Amount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _Amount;
        partial void OnAmountChanging(decimal value);
        partial void OnAmountChanged();
        /// <summary>
        /// There are no comments for Property DataConnectorBudgetTypeName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DataConnectorBudgetTypeName")]
        public virtual string DataConnectorBudgetTypeName
        {
            get
            {
                return this._DataConnectorBudgetTypeName;
            }
            set
            {
                this.OnDataConnectorBudgetTypeNameChanging(value);
                this._DataConnectorBudgetTypeName = value;
                this.OnDataConnectorBudgetTypeNameChanged();
                this.OnPropertyChanged("DataConnectorBudgetTypeName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DataConnectorBudgetTypeName;
        partial void OnDataConnectorBudgetTypeNameChanging(string value);
        partial void OnDataConnectorBudgetTypeNameChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
