//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for CostTransTransferLineTableSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CostTransTransferLineTableSingle")]
    public partial class CostTransTransferLineTableSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<CostTransTransferLineTable>
    {
        /// <summary>
        /// Initialize a new CostTransTransferLineTableSingle object.
        /// </summary>
        public CostTransTransferLineTableSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CostTransTransferLineTableSingle object.
        /// </summary>
        public CostTransTransferLineTableSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CostTransTransferLineTableSingle object.
        /// </summary>
        public CostTransTransferLineTableSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<CostTransTransferLineTable> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for CostTransTransferLineTable in the schema.
    /// </summary>
    /// <KeyProperties>
    /// DataAreaId
    /// ShipDataArea
    /// TransferId
    /// TransferLineNumber
    /// LineNumber
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("dataAreaId", "ShipDataArea", "TransferId", "TransferLineNumber", "LineNumber")]
    [global::Microsoft.OData.Client.EntitySet("CostTransTransferLineTables")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("CostTransTransferLineTable")]
    public partial class CostTransTransferLineTable : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CostTransTransferLineTable object.
        /// </summary>
        /// <param name="dataAreaId">Initial value of DataAreaId.</param>
        /// <param name="shipDataArea">Initial value of ShipDataArea.</param>
        /// <param name="transferId">Initial value of TransferId.</param>
        /// <param name="transferLineNumber">Initial value of TransferLineNumber.</param>
        /// <param name="lineNumber">Initial value of LineNumber.</param>
        /// <param name="costValue">Initial value of CostValue.</param>
        /// <param name="adjustmentAmount">Initial value of AdjustmentAmount.</param>
        /// <param name="minCostAmount">Initial value of MinCostAmount.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static CostTransTransferLineTable CreateCostTransTransferLineTable(string dataAreaId, 
                    string shipDataArea, 
                    string transferId, 
                    decimal transferLineNumber, 
                    decimal lineNumber, 
                    decimal costValue, 
                    decimal adjustmentAmount, 
                    decimal minCostAmount)
        {
            CostTransTransferLineTable costTransTransferLineTable = new CostTransTransferLineTable();
            costTransTransferLineTable.DataAreaId = dataAreaId;
            costTransTransferLineTable.ShipDataArea = shipDataArea;
            costTransTransferLineTable.TransferId = transferId;
            costTransTransferLineTable.TransferLineNumber = transferLineNumber;
            costTransTransferLineTable.LineNumber = lineNumber;
            costTransTransferLineTable.CostValue = costValue;
            costTransTransferLineTable.AdjustmentAmount = adjustmentAmount;
            costTransTransferLineTable.MinCostAmount = minCostAmount;
            return costTransTransferLineTable;
        }
        /// <summary>
        /// There are no comments for Property DataAreaId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("dataAreaId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "DataAreaId is required.")]
        public virtual string DataAreaId
        {
            get
            {
                return this._DataAreaId;
            }
            set
            {
                this.OnDataAreaIdChanging(value);
                this._DataAreaId = value;
                this.OnDataAreaIdChanged();
                this.OnPropertyChanged("dataAreaId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DataAreaId;
        partial void OnDataAreaIdChanging(string value);
        partial void OnDataAreaIdChanged();
        /// <summary>
        /// There are no comments for Property ShipDataArea in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipDataArea")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ShipDataArea is required.")]
        public virtual string ShipDataArea
        {
            get
            {
                return this._ShipDataArea;
            }
            set
            {
                this.OnShipDataAreaChanging(value);
                this._ShipDataArea = value;
                this.OnShipDataAreaChanged();
                this.OnPropertyChanged("ShipDataArea");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ShipDataArea;
        partial void OnShipDataAreaChanging(string value);
        partial void OnShipDataAreaChanged();
        /// <summary>
        /// There are no comments for Property TransferId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TransferId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "TransferId is required.")]
        public virtual string TransferId
        {
            get
            {
                return this._TransferId;
            }
            set
            {
                this.OnTransferIdChanging(value);
                this._TransferId = value;
                this.OnTransferIdChanged();
                this.OnPropertyChanged("TransferId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TransferId;
        partial void OnTransferIdChanging(string value);
        partial void OnTransferIdChanged();
        /// <summary>
        /// There are no comments for Property TransferLineNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TransferLineNumber")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "TransferLineNumber is required.")]
        public virtual decimal TransferLineNumber
        {
            get
            {
                return this._TransferLineNumber;
            }
            set
            {
                this.OnTransferLineNumberChanging(value);
                this._TransferLineNumber = value;
                this.OnTransferLineNumberChanged();
                this.OnPropertyChanged("TransferLineNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _TransferLineNumber;
        partial void OnTransferLineNumberChanging(decimal value);
        partial void OnTransferLineNumberChanged();
        /// <summary>
        /// There are no comments for Property LineNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LineNumber")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "LineNumber is required.")]
        public virtual decimal LineNumber
        {
            get
            {
                return this._LineNumber;
            }
            set
            {
                this.OnLineNumberChanging(value);
                this._LineNumber = value;
                this.OnLineNumberChanged();
                this.OnPropertyChanged("LineNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _LineNumber;
        partial void OnLineNumberChanging(decimal value);
        partial void OnLineNumberChanged();
        /// <summary>
        /// There are no comments for Property ShipCostTypeId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipCostTypeId")]
        public virtual string ShipCostTypeId
        {
            get
            {
                return this._ShipCostTypeId;
            }
            set
            {
                this.OnShipCostTypeIdChanging(value);
                this._ShipCostTypeId = value;
                this.OnShipCostTypeIdChanged();
                this.OnPropertyChanged("ShipCostTypeId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ShipCostTypeId;
        partial void OnShipCostTypeIdChanging(string value);
        partial void OnShipCostTypeIdChanged();
        /// <summary>
        /// There are no comments for Property CurrencyCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CurrencyCode")]
        public virtual string CurrencyCode
        {
            get
            {
                return this._CurrencyCode;
            }
            set
            {
                this.OnCurrencyCodeChanging(value);
                this._CurrencyCode = value;
                this.OnCurrencyCodeChanged();
                this.OnPropertyChanged("CurrencyCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _CurrencyCode;
        partial void OnCurrencyCodeChanging(string value);
        partial void OnCurrencyCodeChanged();
        /// <summary>
        /// There are no comments for Property CostValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CostValue")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "CostValue is required.")]
        public virtual decimal CostValue
        {
            get
            {
                return this._CostValue;
            }
            set
            {
                this.OnCostValueChanging(value);
                this._CostValue = value;
                this.OnCostValueChanged();
                this.OnPropertyChanged("CostValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _CostValue;
        partial void OnCostValueChanging(decimal value);
        partial void OnCostValueChanged();
        /// <summary>
        /// There are no comments for Property ValueAdjustmentMethod in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ValueAdjustmentMethod")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.ITMCostValueAdjustment> ValueAdjustmentMethod
        {
            get
            {
                return this._ValueAdjustmentMethod;
            }
            set
            {
                this.OnValueAdjustmentMethodChanging(value);
                this._ValueAdjustmentMethod = value;
                this.OnValueAdjustmentMethodChanged();
                this.OnPropertyChanged("ValueAdjustmentMethod");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.ITMCostValueAdjustment> _ValueAdjustmentMethod;
        partial void OnValueAdjustmentMethodChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.ITMCostValueAdjustment> value);
        partial void OnValueAdjustmentMethodChanged();
        /// <summary>
        /// There are no comments for Property ShipCostCategory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipCostCategory")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.ITMCostCategory> ShipCostCategory
        {
            get
            {
                return this._ShipCostCategory;
            }
            set
            {
                this.OnShipCostCategoryChanging(value);
                this._ShipCostCategory = value;
                this.OnShipCostCategoryChanged();
                this.OnPropertyChanged("ShipCostCategory");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.ITMCostCategory> _ShipCostCategory;
        partial void OnShipCostCategoryChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.ITMCostCategory> value);
        partial void OnShipCostCategoryChanged();
        /// <summary>
        /// There are no comments for Property ApportionmentMethod in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ApportionmentMethod")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.ITMCostApportionmentMethod> ApportionmentMethod
        {
            get
            {
                return this._ApportionmentMethod;
            }
            set
            {
                this.OnApportionmentMethodChanging(value);
                this._ApportionmentMethod = value;
                this.OnApportionmentMethodChanged();
                this.OnPropertyChanged("ApportionmentMethod");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.ITMCostApportionmentMethod> _ApportionmentMethod;
        partial void OnApportionmentMethodChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.ITMCostApportionmentMethod> value);
        partial void OnApportionmentMethodChanged();
        /// <summary>
        /// There are no comments for Property AdjustmentAmount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AdjustmentAmount")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "AdjustmentAmount is required.")]
        public virtual decimal AdjustmentAmount
        {
            get
            {
                return this._AdjustmentAmount;
            }
            set
            {
                this.OnAdjustmentAmountChanging(value);
                this._AdjustmentAmount = value;
                this.OnAdjustmentAmountChanged();
                this.OnPropertyChanged("AdjustmentAmount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _AdjustmentAmount;
        partial void OnAdjustmentAmountChanging(decimal value);
        partial void OnAdjustmentAmountChanged();
        /// <summary>
        /// There are no comments for Property TaxItemGroup in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TaxItemGroup")]
        public virtual string TaxItemGroup
        {
            get
            {
                return this._TaxItemGroup;
            }
            set
            {
                this.OnTaxItemGroupChanging(value);
                this._TaxItemGroup = value;
                this.OnTaxItemGroupChanged();
                this.OnPropertyChanged("TaxItemGroup");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TaxItemGroup;
        partial void OnTaxItemGroupChanging(string value);
        partial void OnTaxItemGroupChanged();
        /// <summary>
        /// There are no comments for Property LinkCostTypeId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LinkCostTypeId")]
        public virtual string LinkCostTypeId
        {
            get
            {
                return this._LinkCostTypeId;
            }
            set
            {
                this.OnLinkCostTypeIdChanging(value);
                this._LinkCostTypeId = value;
                this.OnLinkCostTypeIdChanged();
                this.OnPropertyChanged("LinkCostTypeId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _LinkCostTypeId;
        partial void OnLinkCostTypeIdChanging(string value);
        partial void OnLinkCostTypeIdChanged();
        /// <summary>
        /// There are no comments for Property MinCostAmount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("MinCostAmount")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "MinCostAmount is required.")]
        public virtual decimal MinCostAmount
        {
            get
            {
                return this._MinCostAmount;
            }
            set
            {
                this.OnMinCostAmountChanging(value);
                this._MinCostAmount = value;
                this.OnMinCostAmountChanged();
                this.OnPropertyChanged("MinCostAmount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _MinCostAmount;
        partial void OnMinCostAmountChanging(decimal value);
        partial void OnMinCostAmountChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
