//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for CredManRiskGroupType in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CredManRiskGroupType")]
    public enum CredManRiskGroupType
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("User")]
        User = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("AveragePaymentDays")]
        AveragePaymentDays = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("CustomerSince")]
        CustomerSince = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("InBusinessSince")]
        InBusinessSince = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("DSO")]
        DSO = 4,
        [global::Microsoft.OData.Client.OriginalNameAttribute("AverageBalance")]
        AverageBalance = 5,
        [global::Microsoft.OData.Client.OriginalNameAttribute("CreditManagementGroup")]
        CreditManagementGroup = 6,
        [global::Microsoft.OData.Client.OriginalNameAttribute("AccountStatus")]
        AccountStatus = 7,
        [global::Microsoft.OData.Client.OriginalNameAttribute("CountryRegion")]
        CountryRegion = 8
    }
}
