//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for DepreciationRateSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DepreciationRateSingle")]
    public partial class DepreciationRateSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<DepreciationRate>
    {
        /// <summary>
        /// Initialize a new DepreciationRateSingle object.
        /// </summary>
        public DepreciationRateSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new DepreciationRateSingle object.
        /// </summary>
        public DepreciationRateSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new DepreciationRateSingle object.
        /// </summary>
        public DepreciationRateSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<DepreciationRate> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for DepreciationRate in the schema.
    /// </summary>
    /// <KeyProperties>
    /// DataAreaId
    /// Name
    /// UsefulLife
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("dataAreaId", "Name", "UsefulLife")]
    [global::Microsoft.OData.Client.EntitySet("DepreciationRates")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("DepreciationRate")]
    public partial class DepreciationRate : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DepreciationRate object.
        /// </summary>
        /// <param name="dataAreaId">Initial value of DataAreaId.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="usefulLife">Initial value of UsefulLife.</param>
        /// <param name="oSLDepRate">Initial value of OSLDepRate.</param>
        /// <param name="nDB250GuaranteedDepRate">Initial value of NDB250GuaranteedDepRate.</param>
        /// <param name="nDB200DepRate">Initial value of NDB200DepRate.</param>
        /// <param name="nDB250DepRate">Initial value of NDB250DepRate.</param>
        /// <param name="nDB200RevisedDepRate">Initial value of NDB200RevisedDepRate.</param>
        /// <param name="electronicDepRate">Initial value of ElectronicDepRate.</param>
        /// <param name="oDBDepRate">Initial value of ODBDepRate.</param>
        /// <param name="nDB250RevisedDepRate">Initial value of NDB250RevisedDepRate.</param>
        /// <param name="nSLDepRate">Initial value of NSLDepRate.</param>
        /// <param name="nDB200GuaranteedDepRate">Initial value of NDB200GuaranteedDepRate.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static DepreciationRate CreateDepreciationRate(string dataAreaId, 
                    string name, 
                    decimal usefulLife, 
                    decimal oSLDepRate, 
                    decimal nDB250GuaranteedDepRate, 
                    decimal nDB200DepRate, 
                    decimal nDB250DepRate, 
                    decimal nDB200RevisedDepRate, 
                    decimal electronicDepRate, 
                    decimal oDBDepRate, 
                    decimal nDB250RevisedDepRate, 
                    decimal nSLDepRate, 
                    decimal nDB200GuaranteedDepRate)
        {
            DepreciationRate depreciationRate = new DepreciationRate();
            depreciationRate.DataAreaId = dataAreaId;
            depreciationRate.Name = name;
            depreciationRate.UsefulLife = usefulLife;
            depreciationRate.OSLDepRate = oSLDepRate;
            depreciationRate.NDB250GuaranteedDepRate = nDB250GuaranteedDepRate;
            depreciationRate.NDB200DepRate = nDB200DepRate;
            depreciationRate.NDB250DepRate = nDB250DepRate;
            depreciationRate.NDB200RevisedDepRate = nDB200RevisedDepRate;
            depreciationRate.ElectronicDepRate = electronicDepRate;
            depreciationRate.ODBDepRate = oDBDepRate;
            depreciationRate.NDB250RevisedDepRate = nDB250RevisedDepRate;
            depreciationRate.NSLDepRate = nSLDepRate;
            depreciationRate.NDB200GuaranteedDepRate = nDB200GuaranteedDepRate;
            return depreciationRate;
        }
        /// <summary>
        /// There are no comments for Property DataAreaId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("dataAreaId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "DataAreaId is required.")]
        public virtual string DataAreaId
        {
            get
            {
                return this._DataAreaId;
            }
            set
            {
                this.OnDataAreaIdChanging(value);
                this._DataAreaId = value;
                this.OnDataAreaIdChanged();
                this.OnPropertyChanged("dataAreaId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DataAreaId;
        partial void OnDataAreaIdChanging(string value);
        partial void OnDataAreaIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Name is required.")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property UsefulLife in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("UsefulLife")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "UsefulLife is required.")]
        public virtual decimal UsefulLife
        {
            get
            {
                return this._UsefulLife;
            }
            set
            {
                this.OnUsefulLifeChanging(value);
                this._UsefulLife = value;
                this.OnUsefulLifeChanged();
                this.OnPropertyChanged("UsefulLife");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _UsefulLife;
        partial void OnUsefulLifeChanging(decimal value);
        partial void OnUsefulLifeChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Description")]
        public virtual string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property OSLDepRate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("OSLDepRate")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "OSLDepRate is required.")]
        public virtual decimal OSLDepRate
        {
            get
            {
                return this._OSLDepRate;
            }
            set
            {
                this.OnOSLDepRateChanging(value);
                this._OSLDepRate = value;
                this.OnOSLDepRateChanged();
                this.OnPropertyChanged("OSLDepRate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _OSLDepRate;
        partial void OnOSLDepRateChanging(decimal value);
        partial void OnOSLDepRateChanged();
        /// <summary>
        /// There are no comments for Property NDB250GuaranteedDepRate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("NDB250GuaranteedDepRate")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "NDB250GuaranteedDepRate is required.")]
        public virtual decimal NDB250GuaranteedDepRate
        {
            get
            {
                return this._NDB250GuaranteedDepRate;
            }
            set
            {
                this.OnNDB250GuaranteedDepRateChanging(value);
                this._NDB250GuaranteedDepRate = value;
                this.OnNDB250GuaranteedDepRateChanged();
                this.OnPropertyChanged("NDB250GuaranteedDepRate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _NDB250GuaranteedDepRate;
        partial void OnNDB250GuaranteedDepRateChanging(decimal value);
        partial void OnNDB250GuaranteedDepRateChanged();
        /// <summary>
        /// There are no comments for Property NDB200DepRate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("NDB200DepRate")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "NDB200DepRate is required.")]
        public virtual decimal NDB200DepRate
        {
            get
            {
                return this._NDB200DepRate;
            }
            set
            {
                this.OnNDB200DepRateChanging(value);
                this._NDB200DepRate = value;
                this.OnNDB200DepRateChanged();
                this.OnPropertyChanged("NDB200DepRate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _NDB200DepRate;
        partial void OnNDB200DepRateChanging(decimal value);
        partial void OnNDB200DepRateChanged();
        /// <summary>
        /// There are no comments for Property NDB250DepRate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("NDB250DepRate")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "NDB250DepRate is required.")]
        public virtual decimal NDB250DepRate
        {
            get
            {
                return this._NDB250DepRate;
            }
            set
            {
                this.OnNDB250DepRateChanging(value);
                this._NDB250DepRate = value;
                this.OnNDB250DepRateChanged();
                this.OnPropertyChanged("NDB250DepRate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _NDB250DepRate;
        partial void OnNDB250DepRateChanging(decimal value);
        partial void OnNDB250DepRateChanged();
        /// <summary>
        /// There are no comments for Property NDB200RevisedDepRate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("NDB200RevisedDepRate")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "NDB200RevisedDepRate is required.")]
        public virtual decimal NDB200RevisedDepRate
        {
            get
            {
                return this._NDB200RevisedDepRate;
            }
            set
            {
                this.OnNDB200RevisedDepRateChanging(value);
                this._NDB200RevisedDepRate = value;
                this.OnNDB200RevisedDepRateChanged();
                this.OnPropertyChanged("NDB200RevisedDepRate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _NDB200RevisedDepRate;
        partial void OnNDB200RevisedDepRateChanging(decimal value);
        partial void OnNDB200RevisedDepRateChanged();
        /// <summary>
        /// There are no comments for Property ElectronicDepRate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ElectronicDepRate")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ElectronicDepRate is required.")]
        public virtual decimal ElectronicDepRate
        {
            get
            {
                return this._ElectronicDepRate;
            }
            set
            {
                this.OnElectronicDepRateChanging(value);
                this._ElectronicDepRate = value;
                this.OnElectronicDepRateChanged();
                this.OnPropertyChanged("ElectronicDepRate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _ElectronicDepRate;
        partial void OnElectronicDepRateChanging(decimal value);
        partial void OnElectronicDepRateChanged();
        /// <summary>
        /// There are no comments for Property ODBDepRate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ODBDepRate")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ODBDepRate is required.")]
        public virtual decimal ODBDepRate
        {
            get
            {
                return this._ODBDepRate;
            }
            set
            {
                this.OnODBDepRateChanging(value);
                this._ODBDepRate = value;
                this.OnODBDepRateChanged();
                this.OnPropertyChanged("ODBDepRate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _ODBDepRate;
        partial void OnODBDepRateChanging(decimal value);
        partial void OnODBDepRateChanged();
        /// <summary>
        /// There are no comments for Property NDB250RevisedDepRate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("NDB250RevisedDepRate")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "NDB250RevisedDepRate is required.")]
        public virtual decimal NDB250RevisedDepRate
        {
            get
            {
                return this._NDB250RevisedDepRate;
            }
            set
            {
                this.OnNDB250RevisedDepRateChanging(value);
                this._NDB250RevisedDepRate = value;
                this.OnNDB250RevisedDepRateChanged();
                this.OnPropertyChanged("NDB250RevisedDepRate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _NDB250RevisedDepRate;
        partial void OnNDB250RevisedDepRateChanging(decimal value);
        partial void OnNDB250RevisedDepRateChanged();
        /// <summary>
        /// There are no comments for Property NSLDepRate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("NSLDepRate")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "NSLDepRate is required.")]
        public virtual decimal NSLDepRate
        {
            get
            {
                return this._NSLDepRate;
            }
            set
            {
                this.OnNSLDepRateChanging(value);
                this._NSLDepRate = value;
                this.OnNSLDepRateChanged();
                this.OnPropertyChanged("NSLDepRate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _NSLDepRate;
        partial void OnNSLDepRateChanging(decimal value);
        partial void OnNSLDepRateChanged();
        /// <summary>
        /// There are no comments for Property NDB200GuaranteedDepRate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("NDB200GuaranteedDepRate")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "NDB200GuaranteedDepRate is required.")]
        public virtual decimal NDB200GuaranteedDepRate
        {
            get
            {
                return this._NDB200GuaranteedDepRate;
            }
            set
            {
                this.OnNDB200GuaranteedDepRateChanging(value);
                this._NDB200GuaranteedDepRate = value;
                this.OnNDB200GuaranteedDepRateChanged();
                this.OnPropertyChanged("NDB200GuaranteedDepRate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _NDB200GuaranteedDepRate;
        partial void OnNDB200GuaranteedDepRateChanging(decimal value);
        partial void OnNDB200GuaranteedDepRateChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
