//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for DiscussionSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DiscussionSingle")]
    public partial class DiscussionSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Discussion>
    {
        /// <summary>
        /// Initialize a new DiscussionSingle object.
        /// </summary>
        public DiscussionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new DiscussionSingle object.
        /// </summary>
        public DiscussionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new DiscussionSingle object.
        /// </summary>
        public DiscussionSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Discussion> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Goals in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Goals")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.DiscussionGoal> Goals
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Goals == null))
                {
                    this._Goals = Context.CreateQuery<global::Microsoft.Dynamics.DataEntities.DiscussionGoal>(GetPath("Goals"));
                }
                return this._Goals;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.DiscussionGoal> _Goals;
        /// <summary>
        /// There are no comments for Topics in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Topics")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.DiscussionTopic> Topics
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Topics == null))
                {
                    this._Topics = Context.CreateQuery<global::Microsoft.Dynamics.DataEntities.DiscussionTopic>(GetPath("Topics"));
                }
                return this._Topics;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.DiscussionTopic> _Topics;
        /// <summary>
        /// There are no comments for PerformanceJournalEntryRelations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PerformanceJournalEntryRelations")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.DiscussionPerformanceJournalEntry> PerformanceJournalEntryRelations
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._PerformanceJournalEntryRelations == null))
                {
                    this._PerformanceJournalEntryRelations = Context.CreateQuery<global::Microsoft.Dynamics.DataEntities.DiscussionPerformanceJournalEntry>(GetPath("PerformanceJournalEntryRelations"));
                }
                return this._PerformanceJournalEntryRelations;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.DiscussionPerformanceJournalEntry> _PerformanceJournalEntryRelations;
        /// <summary>
        /// There are no comments for GoalComments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("GoalComments")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.DiscussionGoalComment> GoalComments
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._GoalComments == null))
                {
                    this._GoalComments = Context.CreateQuery<global::Microsoft.Dynamics.DataEntities.DiscussionGoalComment>(GetPath("GoalComments"));
                }
                return this._GoalComments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.DiscussionGoalComment> _GoalComments;
        /// <summary>
        /// There are no comments for RatingModel in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RatingModel")]
        public virtual global::Microsoft.Dynamics.DataEntities.RatingModelSingle RatingModel
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._RatingModel == null))
                {
                    this._RatingModel = new global::Microsoft.Dynamics.DataEntities.RatingModelSingle(this.Context, GetPath("RatingModel"));
                }
                return this._RatingModel;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.RatingModelSingle _RatingModel;
        /// <summary>
        /// There are no comments for PerfPeriod in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PerfPeriod")]
        public virtual global::Microsoft.Dynamics.DataEntities.PerfPeriodSingle PerfPeriod
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._PerfPeriod == null))
                {
                    this._PerfPeriod = new global::Microsoft.Dynamics.DataEntities.PerfPeriodSingle(this.Context, GetPath("PerfPeriod"));
                }
                return this._PerfPeriod;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.PerfPeriodSingle _PerfPeriod;
        /// <summary>
        /// There are no comments for RatingLevel in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RatingLevel")]
        public virtual global::Microsoft.Dynamics.DataEntities.RatingLevelSingle RatingLevel
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._RatingLevel == null))
                {
                    this._RatingLevel = new global::Microsoft.Dynamics.DataEntities.RatingLevelSingle(this.Context, GetPath("RatingLevel"));
                }
                return this._RatingLevel;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.RatingLevelSingle _RatingLevel;
        /// <summary>
        /// There are no comments for Worker in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Worker")]
        public virtual global::Microsoft.Dynamics.DataEntities.WorkerSingle Worker
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Worker == null))
                {
                    this._Worker = new global::Microsoft.Dynamics.DataEntities.WorkerSingle(this.Context, GetPath("Worker"));
                }
                return this._Worker;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.WorkerSingle _Worker;
        /// <summary>
        /// There are no comments for HcmDiscussionType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("HcmDiscussionType")]
        public virtual global::Microsoft.Dynamics.DataEntities.DiscussionTypeSingle HcmDiscussionType
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._HcmDiscussionType == null))
                {
                    this._HcmDiscussionType = new global::Microsoft.Dynamics.DataEntities.DiscussionTypeSingle(this.Context, GetPath("HcmDiscussionType"));
                }
                return this._HcmDiscussionType;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.DiscussionTypeSingle _HcmDiscussionType;
        /// <summary>
        /// There are no comments for TopicComments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TopicComments")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.DiscussionTopicComment> TopicComments
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._TopicComments == null))
                {
                    this._TopicComments = Context.CreateQuery<global::Microsoft.Dynamics.DataEntities.DiscussionTopicComment>(GetPath("TopicComments"));
                }
                return this._TopicComments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.DiscussionTopicComment> _TopicComments;
        /// <summary>
        /// There are no comments for Measurements in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Measurements")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.DiscussionMeasurement> Measurements
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Measurements == null))
                {
                    this._Measurements = Context.CreateQuery<global::Microsoft.Dynamics.DataEntities.DiscussionMeasurement>(GetPath("Measurements"));
                }
                return this._Measurements;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.DiscussionMeasurement> _Measurements;
        /// <summary>
        /// There are no comments for OverallComments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("OverallComments")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.DiscussionOverallComment> OverallComments
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._OverallComments == null))
                {
                    this._OverallComments = Context.CreateQuery<global::Microsoft.Dynamics.DataEntities.DiscussionOverallComment>(GetPath("OverallComments"));
                }
                return this._OverallComments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.DiscussionOverallComment> _OverallComments;
        /// <summary>
        /// There are no comments for SignOffs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SignOffs")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.DiscussionSignOff> SignOffs
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._SignOffs == null))
                {
                    this._SignOffs = Context.CreateQuery<global::Microsoft.Dynamics.DataEntities.DiscussionSignOff>(GetPath("SignOffs"));
                }
                return this._SignOffs;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.DiscussionSignOff> _SignOffs;
    }
    /// <summary>
    /// There are no comments for Discussion in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Discussion
    /// PersonnelNumber
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Discussion", "PersonnelNumber")]
    [global::Microsoft.OData.Client.EntitySet("Discussions")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Discussion")]
    public partial class Discussion : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Discussion object.
        /// </summary>
        /// <param name="discussion1">Initial value of Discussion1.</param>
        /// <param name="personnelNumber">Initial value of PersonnelNumber.</param>
        /// <param name="finishedDate">Initial value of FinishedDate.</param>
        /// <param name="totalRatingScore">Initial value of TotalRatingScore.</param>
        /// <param name="averageRatingScore">Initial value of AverageRatingScore.</param>
        /// <param name="startDate">Initial value of StartDate.</param>
        /// <param name="endDate">Initial value of EndDate.</param>
        /// <param name="perfPeriod">Initial value of PerfPeriod.</param>
        /// <param name="ratingLevel">Initial value of RatingLevel.</param>
        /// <param name="worker">Initial value of Worker.</param>
        /// <param name="hcmDiscussionType">Initial value of HcmDiscussionType.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Discussion CreateDiscussion(string discussion1, 
                    string personnelNumber, 
                    global::System.DateTimeOffset finishedDate, 
                    decimal totalRatingScore, 
                    decimal averageRatingScore, 
                    global::System.DateTimeOffset startDate, 
                    global::System.DateTimeOffset endDate, 
                    global::Microsoft.Dynamics.DataEntities.PerfPeriod perfPeriod, 
                    global::Microsoft.Dynamics.DataEntities.RatingLevel ratingLevel, 
                    global::Microsoft.Dynamics.DataEntities.Worker worker, 
                    global::Microsoft.Dynamics.DataEntities.DiscussionType hcmDiscussionType)
        {
            Discussion discussion = new Discussion();
            discussion.Discussion1 = discussion1;
            discussion.PersonnelNumber = personnelNumber;
            discussion.FinishedDate = finishedDate;
            discussion.TotalRatingScore = totalRatingScore;
            discussion.AverageRatingScore = averageRatingScore;
            discussion.StartDate = startDate;
            discussion.EndDate = endDate;
            if ((perfPeriod == null))
            {
                throw new global::System.ArgumentNullException("perfPeriod");
            }
            discussion.PerfPeriod = perfPeriod;
            if ((ratingLevel == null))
            {
                throw new global::System.ArgumentNullException("ratingLevel");
            }
            discussion.RatingLevel = ratingLevel;
            if ((worker == null))
            {
                throw new global::System.ArgumentNullException("worker");
            }
            discussion.Worker = worker;
            if ((hcmDiscussionType == null))
            {
                throw new global::System.ArgumentNullException("hcmDiscussionType");
            }
            discussion.HcmDiscussionType = hcmDiscussionType;
            return discussion;
        }
        /// <summary>
        /// There are no comments for Property Discussion1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Discussion")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Discussion1 is required.")]
        public virtual string Discussion1
        {
            get
            {
                return this._Discussion1;
            }
            set
            {
                this.OnDiscussion1Changing(value);
                this._Discussion1 = value;
                this.OnDiscussion1Changed();
                this.OnPropertyChanged("Discussion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Discussion1;
        partial void OnDiscussion1Changing(string value);
        partial void OnDiscussion1Changed();
        /// <summary>
        /// There are no comments for Property PersonnelNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PersonnelNumber")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "PersonnelNumber is required.")]
        public virtual string PersonnelNumber
        {
            get
            {
                return this._PersonnelNumber;
            }
            set
            {
                this.OnPersonnelNumberChanging(value);
                this._PersonnelNumber = value;
                this.OnPersonnelNumberChanged();
                this.OnPropertyChanged("PersonnelNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PersonnelNumber;
        partial void OnPersonnelNumberChanging(string value);
        partial void OnPersonnelNumberChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Description")]
        public virtual string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property PerformancePeriodId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PerformancePeriodId")]
        public virtual string PerformancePeriodId
        {
            get
            {
                return this._PerformancePeriodId;
            }
            set
            {
                this.OnPerformancePeriodIdChanging(value);
                this._PerformancePeriodId = value;
                this.OnPerformancePeriodIdChanged();
                this.OnPropertyChanged("PerformancePeriodId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PerformancePeriodId;
        partial void OnPerformancePeriodIdChanging(string value);
        partial void OnPerformancePeriodIdChanged();
        /// <summary>
        /// There are no comments for Property Comments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Comments")]
        public virtual string Comments
        {
            get
            {
                return this._Comments;
            }
            set
            {
                this.OnCommentsChanging(value);
                this._Comments = value;
                this.OnCommentsChanged();
                this.OnPropertyChanged("Comments");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Comments;
        partial void OnCommentsChanging(string value);
        partial void OnCommentsChanged();
        /// <summary>
        /// There are no comments for Property DiscussionApprovalStatus in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DiscussionApprovalStatus")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.HcmDiscussionApproveStatus> DiscussionApprovalStatus
        {
            get
            {
                return this._DiscussionApprovalStatus;
            }
            set
            {
                this.OnDiscussionApprovalStatusChanging(value);
                this._DiscussionApprovalStatus = value;
                this.OnDiscussionApprovalStatusChanged();
                this.OnPropertyChanged("DiscussionApprovalStatus");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.HcmDiscussionApproveStatus> _DiscussionApprovalStatus;
        partial void OnDiscussionApprovalStatusChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.HcmDiscussionApproveStatus> value);
        partial void OnDiscussionApprovalStatusChanged();
        /// <summary>
        /// There are no comments for Property FinalEmployeeRatingId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FinalEmployeeRatingId")]
        public virtual string FinalEmployeeRatingId
        {
            get
            {
                return this._FinalEmployeeRatingId;
            }
            set
            {
                this.OnFinalEmployeeRatingIdChanging(value);
                this._FinalEmployeeRatingId = value;
                this.OnFinalEmployeeRatingIdChanged();
                this.OnPropertyChanged("FinalEmployeeRatingId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _FinalEmployeeRatingId;
        partial void OnFinalEmployeeRatingIdChanging(string value);
        partial void OnFinalEmployeeRatingIdChanged();
        /// <summary>
        /// There are no comments for Property FinishedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FinishedDate")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "FinishedDate is required.")]
        public virtual global::System.DateTimeOffset FinishedDate
        {
            get
            {
                return this._FinishedDate;
            }
            set
            {
                this.OnFinishedDateChanging(value);
                this._FinishedDate = value;
                this.OnFinishedDateChanged();
                this.OnPropertyChanged("FinishedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _FinishedDate;
        partial void OnFinishedDateChanging(global::System.DateTimeOffset value);
        partial void OnFinishedDateChanged();
        /// <summary>
        /// There are no comments for Property ReviewTypeId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ReviewTypeId")]
        public virtual string ReviewTypeId
        {
            get
            {
                return this._ReviewTypeId;
            }
            set
            {
                this.OnReviewTypeIdChanging(value);
                this._ReviewTypeId = value;
                this.OnReviewTypeIdChanged();
                this.OnPropertyChanged("ReviewTypeId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ReviewTypeId;
        partial void OnReviewTypeIdChanging(string value);
        partial void OnReviewTypeIdChanged();
        /// <summary>
        /// There are no comments for Property TotalRatingScore in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TotalRatingScore")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "TotalRatingScore is required.")]
        public virtual decimal TotalRatingScore
        {
            get
            {
                return this._TotalRatingScore;
            }
            set
            {
                this.OnTotalRatingScoreChanging(value);
                this._TotalRatingScore = value;
                this.OnTotalRatingScoreChanged();
                this.OnPropertyChanged("TotalRatingScore");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _TotalRatingScore;
        partial void OnTotalRatingScoreChanging(decimal value);
        partial void OnTotalRatingScoreChanged();
        /// <summary>
        /// There are no comments for Property WorkflowEnabled in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("WorkflowEnabled")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> WorkflowEnabled
        {
            get
            {
                return this._WorkflowEnabled;
            }
            set
            {
                this.OnWorkflowEnabledChanging(value);
                this._WorkflowEnabled = value;
                this.OnWorkflowEnabledChanged();
                this.OnPropertyChanged("WorkflowEnabled");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _WorkflowEnabled;
        partial void OnWorkflowEnabledChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnWorkflowEnabledChanged();
        /// <summary>
        /// There are no comments for Property AverageRatingScore in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AverageRatingScore")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "AverageRatingScore is required.")]
        public virtual decimal AverageRatingScore
        {
            get
            {
                return this._AverageRatingScore;
            }
            set
            {
                this.OnAverageRatingScoreChanging(value);
                this._AverageRatingScore = value;
                this.OnAverageRatingScoreChanged();
                this.OnPropertyChanged("AverageRatingScore");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _AverageRatingScore;
        partial void OnAverageRatingScoreChanging(decimal value);
        partial void OnAverageRatingScoreChanged();
        /// <summary>
        /// There are no comments for Property RatingModelId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RatingModelId")]
        public virtual string RatingModelId
        {
            get
            {
                return this._RatingModelId;
            }
            set
            {
                this.OnRatingModelIdChanging(value);
                this._RatingModelId = value;
                this.OnRatingModelIdChanged();
                this.OnPropertyChanged("RatingModelId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RatingModelId;
        partial void OnRatingModelIdChanging(string value);
        partial void OnRatingModelIdChanged();
        /// <summary>
        /// There are no comments for Property StartDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("StartDate")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "StartDate is required.")]
        public virtual global::System.DateTimeOffset StartDate
        {
            get
            {
                return this._StartDate;
            }
            set
            {
                this.OnStartDateChanging(value);
                this._StartDate = value;
                this.OnStartDateChanged();
                this.OnPropertyChanged("StartDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _StartDate;
        partial void OnStartDateChanging(global::System.DateTimeOffset value);
        partial void OnStartDateChanged();
        /// <summary>
        /// There are no comments for Property EndDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("EndDate")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "EndDate is required.")]
        public virtual global::System.DateTimeOffset EndDate
        {
            get
            {
                return this._EndDate;
            }
            set
            {
                this.OnEndDateChanging(value);
                this._EndDate = value;
                this.OnEndDateChanged();
                this.OnPropertyChanged("EndDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _EndDate;
        partial void OnEndDateChanging(global::System.DateTimeOffset value);
        partial void OnEndDateChanged();
        /// <summary>
        /// There are no comments for Property Overview in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Overview")]
        public virtual string Overview
        {
            get
            {
                return this._Overview;
            }
            set
            {
                this.OnOverviewChanging(value);
                this._Overview = value;
                this.OnOverviewChanged();
                this.OnPropertyChanged("Overview");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Overview;
        partial void OnOverviewChanging(string value);
        partial void OnOverviewChanged();
        /// <summary>
        /// There are no comments for Property Goals in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Goals")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionGoal> Goals
        {
            get
            {
                return this._Goals;
            }
            set
            {
                this.OnGoalsChanging(value);
                this._Goals = value;
                this.OnGoalsChanged();
                this.OnPropertyChanged("Goals");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionGoal> _Goals = new global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionGoal>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnGoalsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionGoal> value);
        partial void OnGoalsChanged();
        /// <summary>
        /// There are no comments for Property Topics in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Topics")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionTopic> Topics
        {
            get
            {
                return this._Topics;
            }
            set
            {
                this.OnTopicsChanging(value);
                this._Topics = value;
                this.OnTopicsChanged();
                this.OnPropertyChanged("Topics");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionTopic> _Topics = new global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionTopic>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnTopicsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionTopic> value);
        partial void OnTopicsChanged();
        /// <summary>
        /// There are no comments for Property PerformanceJournalEntryRelations in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PerformanceJournalEntryRelations")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionPerformanceJournalEntry> PerformanceJournalEntryRelations
        {
            get
            {
                return this._PerformanceJournalEntryRelations;
            }
            set
            {
                this.OnPerformanceJournalEntryRelationsChanging(value);
                this._PerformanceJournalEntryRelations = value;
                this.OnPerformanceJournalEntryRelationsChanged();
                this.OnPropertyChanged("PerformanceJournalEntryRelations");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionPerformanceJournalEntry> _PerformanceJournalEntryRelations = new global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionPerformanceJournalEntry>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnPerformanceJournalEntryRelationsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionPerformanceJournalEntry> value);
        partial void OnPerformanceJournalEntryRelationsChanged();
        /// <summary>
        /// There are no comments for Property GoalComments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("GoalComments")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionGoalComment> GoalComments
        {
            get
            {
                return this._GoalComments;
            }
            set
            {
                this.OnGoalCommentsChanging(value);
                this._GoalComments = value;
                this.OnGoalCommentsChanged();
                this.OnPropertyChanged("GoalComments");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionGoalComment> _GoalComments = new global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionGoalComment>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnGoalCommentsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionGoalComment> value);
        partial void OnGoalCommentsChanged();
        /// <summary>
        /// There are no comments for Property RatingModel in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RatingModel")]
        public virtual global::Microsoft.Dynamics.DataEntities.RatingModel RatingModel
        {
            get
            {
                return this._RatingModel;
            }
            set
            {
                this.OnRatingModelChanging(value);
                this._RatingModel = value;
                this.OnRatingModelChanged();
                this.OnPropertyChanged("RatingModel");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.RatingModel _RatingModel;
        partial void OnRatingModelChanging(global::Microsoft.Dynamics.DataEntities.RatingModel value);
        partial void OnRatingModelChanged();
        /// <summary>
        /// There are no comments for Property PerfPeriod in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PerfPeriod")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "PerfPeriod is required.")]
        public virtual global::Microsoft.Dynamics.DataEntities.PerfPeriod PerfPeriod
        {
            get
            {
                return this._PerfPeriod;
            }
            set
            {
                this.OnPerfPeriodChanging(value);
                this._PerfPeriod = value;
                this.OnPerfPeriodChanged();
                this.OnPropertyChanged("PerfPeriod");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.PerfPeriod _PerfPeriod;
        partial void OnPerfPeriodChanging(global::Microsoft.Dynamics.DataEntities.PerfPeriod value);
        partial void OnPerfPeriodChanged();
        /// <summary>
        /// There are no comments for Property RatingLevel in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RatingLevel")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "RatingLevel is required.")]
        public virtual global::Microsoft.Dynamics.DataEntities.RatingLevel RatingLevel
        {
            get
            {
                return this._RatingLevel;
            }
            set
            {
                this.OnRatingLevelChanging(value);
                this._RatingLevel = value;
                this.OnRatingLevelChanged();
                this.OnPropertyChanged("RatingLevel");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.RatingLevel _RatingLevel;
        partial void OnRatingLevelChanging(global::Microsoft.Dynamics.DataEntities.RatingLevel value);
        partial void OnRatingLevelChanged();
        /// <summary>
        /// There are no comments for Property Worker in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Worker")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Worker is required.")]
        public virtual global::Microsoft.Dynamics.DataEntities.Worker Worker
        {
            get
            {
                return this._Worker;
            }
            set
            {
                this.OnWorkerChanging(value);
                this._Worker = value;
                this.OnWorkerChanged();
                this.OnPropertyChanged("Worker");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.Worker _Worker;
        partial void OnWorkerChanging(global::Microsoft.Dynamics.DataEntities.Worker value);
        partial void OnWorkerChanged();
        /// <summary>
        /// There are no comments for Property HcmDiscussionType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("HcmDiscussionType")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "HcmDiscussionType is required.")]
        public virtual global::Microsoft.Dynamics.DataEntities.DiscussionType HcmDiscussionType
        {
            get
            {
                return this._HcmDiscussionType;
            }
            set
            {
                this.OnHcmDiscussionTypeChanging(value);
                this._HcmDiscussionType = value;
                this.OnHcmDiscussionTypeChanged();
                this.OnPropertyChanged("HcmDiscussionType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.DiscussionType _HcmDiscussionType;
        partial void OnHcmDiscussionTypeChanging(global::Microsoft.Dynamics.DataEntities.DiscussionType value);
        partial void OnHcmDiscussionTypeChanged();
        /// <summary>
        /// There are no comments for Property TopicComments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TopicComments")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionTopicComment> TopicComments
        {
            get
            {
                return this._TopicComments;
            }
            set
            {
                this.OnTopicCommentsChanging(value);
                this._TopicComments = value;
                this.OnTopicCommentsChanged();
                this.OnPropertyChanged("TopicComments");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionTopicComment> _TopicComments = new global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionTopicComment>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnTopicCommentsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionTopicComment> value);
        partial void OnTopicCommentsChanged();
        /// <summary>
        /// There are no comments for Property Measurements in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Measurements")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionMeasurement> Measurements
        {
            get
            {
                return this._Measurements;
            }
            set
            {
                this.OnMeasurementsChanging(value);
                this._Measurements = value;
                this.OnMeasurementsChanged();
                this.OnPropertyChanged("Measurements");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionMeasurement> _Measurements = new global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionMeasurement>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnMeasurementsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionMeasurement> value);
        partial void OnMeasurementsChanged();
        /// <summary>
        /// There are no comments for Property OverallComments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("OverallComments")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionOverallComment> OverallComments
        {
            get
            {
                return this._OverallComments;
            }
            set
            {
                this.OnOverallCommentsChanging(value);
                this._OverallComments = value;
                this.OnOverallCommentsChanged();
                this.OnPropertyChanged("OverallComments");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionOverallComment> _OverallComments = new global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionOverallComment>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnOverallCommentsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionOverallComment> value);
        partial void OnOverallCommentsChanged();
        /// <summary>
        /// There are no comments for Property SignOffs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SignOffs")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionSignOff> SignOffs
        {
            get
            {
                return this._SignOffs;
            }
            set
            {
                this.OnSignOffsChanging(value);
                this._SignOffs = value;
                this.OnSignOffsChanged();
                this.OnPropertyChanged("SignOffs");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionSignOff> _SignOffs = new global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionSignOff>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnSignOffsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.DiscussionSignOff> value);
        partial void OnSignOffsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
