//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for DMFProjectCategory in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DMFProjectCategory")]
    public enum DMFProjectCategory
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Project")]
        Project = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Configuration")]
        Configuration = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Integration")]
        Integration = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Other")]
        Other = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("CDS")]
        CDS = 4
    }
}
