//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for EcoResCategoryNamedHierarchyRole in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("EcoResCategoryNamedHierarchyRole")]
    public enum EcoResCategoryNamedHierarchyRole
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Procurement")]
        Procurement = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Sales")]
        Sales = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Retail")]
        Retail = 4,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Commodity")]
        Commodity = 5,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Financials")]
        Financials = 7,
        [global::Microsoft.OData.Client.OriginalNameAttribute("RetailSpecialGroup")]
        RetailSpecialGroup = 20,
        [global::Microsoft.OData.Client.OriginalNameAttribute("RetailVendorProductHierarchy")]
        RetailVendorProductHierarchy = 21,
        [global::Microsoft.OData.Client.OriginalNameAttribute("RetailChannelNavigation")]
        RetailChannelNavigation = 22,
        [global::Microsoft.OData.Client.OriginalNameAttribute("PackingMaterials_W")]
        PackingMaterials_W = 23,
        [global::Microsoft.OData.Client.OriginalNameAttribute("CommonDataService")]
        CommonDataService = 24,
        [global::Microsoft.OData.Client.OriginalNameAttribute("CostManagement")]
        CostManagement = 25,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Traceability")]
        Traceability = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("EngineeringProduct")]
        EngineeringProduct = 0
    }
}
