//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for FBContribTransferEvent_BR in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("FBContribTransferEvent_BR")]
    public enum FBContribTransferEvent_BR
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Incorporation")]
        Incorporation = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Merger")]
        Merger = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("TotalDivision")]
        TotalDivision = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("PartialDivision")]
        PartialDivision = 4,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Others")]
        Others = 99
    }
}
