//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for FBSCPType_BR in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("FBSCPType_BR")]
    public enum FBSCPType_BR
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("NonSCP")]
        NonSCP = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("SCPPartner")]
        SCPPartner = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("SCP")]
        SCP = 2
    }
}
