//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for FunctionalityProfileFiscalIntegrationTechnicalProfileLineSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("FunctionalityProfileFiscalIntegrationTechnicalProfileLineSingle")]
    public partial class FunctionalityProfileFiscalIntegrationTechnicalProfileLineSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<FunctionalityProfileFiscalIntegrationTechnicalProfileLine>
    {
        /// <summary>
        /// Initialize a new FunctionalityProfileFiscalIntegrationTechnicalProfileLineSingle object.
        /// </summary>
        public FunctionalityProfileFiscalIntegrationTechnicalProfileLineSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new FunctionalityProfileFiscalIntegrationTechnicalProfileLineSingle object.
        /// </summary>
        public FunctionalityProfileFiscalIntegrationTechnicalProfileLineSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new FunctionalityProfileFiscalIntegrationTechnicalProfileLineSingle object.
        /// </summary>
        public FunctionalityProfileFiscalIntegrationTechnicalProfileLineSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<FunctionalityProfileFiscalIntegrationTechnicalProfileLine> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for FunctionalityProfileFiscalIntegrationTechnicalProfileLine in the schema.
    /// </summary>
    /// <KeyProperties>
    /// FunctionalityProfileId
    /// FiscalTechnicalProfileId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("FunctionalityProfileId", "FiscalTechnicalProfileId")]
    [global::Microsoft.OData.Client.EntitySet("FunctionalityProfileFiscalIntegrationTechnicalProfileLines")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("FunctionalityProfileFiscalIntegrationTechnicalProfileLine")]
    public partial class FunctionalityProfileFiscalIntegrationTechnicalProfileLine : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new FunctionalityProfileFiscalIntegrationTechnicalProfileLine object.
        /// </summary>
        /// <param name="functionalityProfileId">Initial value of FunctionalityProfileId.</param>
        /// <param name="fiscalTechnicalProfileId">Initial value of FiscalTechnicalProfileId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static FunctionalityProfileFiscalIntegrationTechnicalProfileLine CreateFunctionalityProfileFiscalIntegrationTechnicalProfileLine(string functionalityProfileId, string fiscalTechnicalProfileId)
        {
            FunctionalityProfileFiscalIntegrationTechnicalProfileLine functionalityProfileFiscalIntegrationTechnicalProfileLine = new FunctionalityProfileFiscalIntegrationTechnicalProfileLine();
            functionalityProfileFiscalIntegrationTechnicalProfileLine.FunctionalityProfileId = functionalityProfileId;
            functionalityProfileFiscalIntegrationTechnicalProfileLine.FiscalTechnicalProfileId = fiscalTechnicalProfileId;
            return functionalityProfileFiscalIntegrationTechnicalProfileLine;
        }
        /// <summary>
        /// There are no comments for Property FunctionalityProfileId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FunctionalityProfileId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "FunctionalityProfileId is required.")]
        public virtual string FunctionalityProfileId
        {
            get
            {
                return this._FunctionalityProfileId;
            }
            set
            {
                this.OnFunctionalityProfileIdChanging(value);
                this._FunctionalityProfileId = value;
                this.OnFunctionalityProfileIdChanged();
                this.OnPropertyChanged("FunctionalityProfileId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _FunctionalityProfileId;
        partial void OnFunctionalityProfileIdChanging(string value);
        partial void OnFunctionalityProfileIdChanged();
        /// <summary>
        /// There are no comments for Property FiscalTechnicalProfileId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FiscalTechnicalProfileId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "FiscalTechnicalProfileId is required.")]
        public virtual string FiscalTechnicalProfileId
        {
            get
            {
                return this._FiscalTechnicalProfileId;
            }
            set
            {
                this.OnFiscalTechnicalProfileIdChanging(value);
                this._FiscalTechnicalProfileId = value;
                this.OnFiscalTechnicalProfileIdChanged();
                this.OnPropertyChanged("FiscalTechnicalProfileId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _FiscalTechnicalProfileId;
        partial void OnFiscalTechnicalProfileIdChanging(string value);
        partial void OnFiscalTechnicalProfileIdChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
