//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for ITMCostPostingDatePrinciple in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ITMCostPostingDatePrinciple")]
    public enum ITMCostPostingDatePrinciple
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("TransDate")]
        TransDate = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("PurchDateFinancial")]
        PurchDateFinancial = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("SelectedDate")]
        SelectedDate = 2
    }
}
