//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for LedgerLiquiditySingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("LedgerLiquiditySingle")]
    public partial class LedgerLiquiditySingle : global::Microsoft.OData.Client.DataServiceQuerySingle<LedgerLiquidity>
    {
        /// <summary>
        /// Initialize a new LedgerLiquiditySingle object.
        /// </summary>
        public LedgerLiquiditySingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new LedgerLiquiditySingle object.
        /// </summary>
        public LedgerLiquiditySingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new LedgerLiquiditySingle object.
        /// </summary>
        public LedgerLiquiditySingle(global::Microsoft.OData.Client.DataServiceQuerySingle<LedgerLiquidity> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for LedgerLiquidity in the schema.
    /// </summary>
    /// <KeyProperties>
    /// DataAreaId
    /// MainAccountId
    /// ChartOfAccountsName
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("dataAreaId", "MainAccountId", "ChartOfAccountsName")]
    [global::Microsoft.OData.Client.EntitySet("LedgerLiquidities")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("LedgerLiquidity")]
    public partial class LedgerLiquidity : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new LedgerLiquidity object.
        /// </summary>
        /// <param name="dataAreaId">Initial value of DataAreaId.</param>
        /// <param name="mainAccountId">Initial value of MainAccountId.</param>
        /// <param name="chartOfAccountsName">Initial value of ChartOfAccountsName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static LedgerLiquidity CreateLedgerLiquidity(string dataAreaId, string mainAccountId, string chartOfAccountsName)
        {
            LedgerLiquidity ledgerLiquidity = new LedgerLiquidity();
            ledgerLiquidity.DataAreaId = dataAreaId;
            ledgerLiquidity.MainAccountId = mainAccountId;
            ledgerLiquidity.ChartOfAccountsName = chartOfAccountsName;
            return ledgerLiquidity;
        }
        /// <summary>
        /// There are no comments for Property DataAreaId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("dataAreaId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "DataAreaId is required.")]
        public virtual string DataAreaId
        {
            get
            {
                return this._DataAreaId;
            }
            set
            {
                this.OnDataAreaIdChanging(value);
                this._DataAreaId = value;
                this.OnDataAreaIdChanged();
                this.OnPropertyChanged("dataAreaId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DataAreaId;
        partial void OnDataAreaIdChanging(string value);
        partial void OnDataAreaIdChanged();
        /// <summary>
        /// There are no comments for Property MainAccountId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("MainAccountId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "MainAccountId is required.")]
        public virtual string MainAccountId
        {
            get
            {
                return this._MainAccountId;
            }
            set
            {
                this.OnMainAccountIdChanging(value);
                this._MainAccountId = value;
                this.OnMainAccountIdChanged();
                this.OnPropertyChanged("MainAccountId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _MainAccountId;
        partial void OnMainAccountIdChanging(string value);
        partial void OnMainAccountIdChanged();
        /// <summary>
        /// There are no comments for Property ChartOfAccountsName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ChartOfAccountsName")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ChartOfAccountsName is required.")]
        public virtual string ChartOfAccountsName
        {
            get
            {
                return this._ChartOfAccountsName;
            }
            set
            {
                this.OnChartOfAccountsNameChanging(value);
                this._ChartOfAccountsName = value;
                this.OnChartOfAccountsNameChanged();
                this.OnPropertyChanged("ChartOfAccountsName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ChartOfAccountsName;
        partial void OnChartOfAccountsNameChanging(string value);
        partial void OnChartOfAccountsNameChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
