//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for PositionJobSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("PositionJobSingle")]
    public partial class PositionJobSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<PositionJob>
    {
        /// <summary>
        /// Initialize a new PositionJobSingle object.
        /// </summary>
        public PositionJobSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PositionJobSingle object.
        /// </summary>
        public PositionJobSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new PositionJobSingle object.
        /// </summary>
        public PositionJobSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<PositionJob> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for PayrollFixedCompensationPlan in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PayrollFixedCompensationPlan")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.PayrollFixedCompensationPlan> PayrollFixedCompensationPlan
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._PayrollFixedCompensationPlan == null))
                {
                    this._PayrollFixedCompensationPlan = Context.CreateQuery<global::Microsoft.Dynamics.DataEntities.PayrollFixedCompensationPlan>(GetPath("PayrollFixedCompensationPlan"));
                }
                return this._PayrollFixedCompensationPlan;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.DataEntities.PayrollFixedCompensationPlan> _PayrollFixedCompensationPlan;
        /// <summary>
        /// There are no comments for JobDetail in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("JobDetail")]
        public virtual global::Microsoft.Dynamics.DataEntities.JobDetailSingle JobDetail
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._JobDetail == null))
                {
                    this._JobDetail = new global::Microsoft.Dynamics.DataEntities.JobDetailSingle(this.Context, GetPath("JobDetail"));
                }
                return this._JobDetail;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.JobDetailSingle _JobDetail;
        /// <summary>
        /// There are no comments for PayrollPosition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PayrollPosition")]
        public virtual global::Microsoft.Dynamics.DataEntities.PayrollPositionSingle PayrollPosition
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._PayrollPosition == null))
                {
                    this._PayrollPosition = new global::Microsoft.Dynamics.DataEntities.PayrollPositionSingle(this.Context, GetPath("PayrollPosition"));
                }
                return this._PayrollPosition;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.PayrollPositionSingle _PayrollPosition;
    }
    /// <summary>
    /// There are no comments for PositionJob in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PositionId
    /// JobId
    /// ValidFrom
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("PositionId", "JobId", "ValidFrom")]
    [global::Microsoft.OData.Client.EntitySet("PositionJobs")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("PositionJob")]
    public partial class PositionJob : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new PositionJob object.
        /// </summary>
        /// <param name="positionId">Initial value of PositionId.</param>
        /// <param name="jobId">Initial value of JobId.</param>
        /// <param name="validFrom">Initial value of ValidFrom.</param>
        /// <param name="validTo">Initial value of ValidTo.</param>
        /// <param name="jobDetail">Initial value of JobDetail.</param>
        /// <param name="payrollPosition">Initial value of PayrollPosition.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static PositionJob CreatePositionJob(string positionId, 
                    string jobId, 
                    global::System.DateTimeOffset validFrom, 
                    global::System.DateTimeOffset validTo, 
                    global::Microsoft.Dynamics.DataEntities.JobDetail jobDetail, 
                    global::Microsoft.Dynamics.DataEntities.PayrollPosition payrollPosition)
        {
            PositionJob positionJob = new PositionJob();
            positionJob.PositionId = positionId;
            positionJob.JobId = jobId;
            positionJob.ValidFrom = validFrom;
            positionJob.ValidTo = validTo;
            if ((jobDetail == null))
            {
                throw new global::System.ArgumentNullException("jobDetail");
            }
            positionJob.JobDetail = jobDetail;
            if ((payrollPosition == null))
            {
                throw new global::System.ArgumentNullException("payrollPosition");
            }
            positionJob.PayrollPosition = payrollPosition;
            return positionJob;
        }
        /// <summary>
        /// There are no comments for Property PositionId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PositionId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "PositionId is required.")]
        public virtual string PositionId
        {
            get
            {
                return this._PositionId;
            }
            set
            {
                this.OnPositionIdChanging(value);
                this._PositionId = value;
                this.OnPositionIdChanged();
                this.OnPropertyChanged("PositionId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PositionId;
        partial void OnPositionIdChanging(string value);
        partial void OnPositionIdChanged();
        /// <summary>
        /// There are no comments for Property JobId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("JobId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "JobId is required.")]
        public virtual string JobId
        {
            get
            {
                return this._JobId;
            }
            set
            {
                this.OnJobIdChanging(value);
                this._JobId = value;
                this.OnJobIdChanged();
                this.OnPropertyChanged("JobId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _JobId;
        partial void OnJobIdChanging(string value);
        partial void OnJobIdChanged();
        /// <summary>
        /// There are no comments for Property ValidFrom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ValidFrom")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ValidFrom is required.")]
        public virtual global::System.DateTimeOffset ValidFrom
        {
            get
            {
                return this._ValidFrom;
            }
            set
            {
                this.OnValidFromChanging(value);
                this._ValidFrom = value;
                this.OnValidFromChanged();
                this.OnPropertyChanged("ValidFrom");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _ValidFrom;
        partial void OnValidFromChanging(global::System.DateTimeOffset value);
        partial void OnValidFromChanged();
        /// <summary>
        /// There are no comments for Property ValidTo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ValidTo")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ValidTo is required.")]
        public virtual global::System.DateTimeOffset ValidTo
        {
            get
            {
                return this._ValidTo;
            }
            set
            {
                this.OnValidToChanging(value);
                this._ValidTo = value;
                this.OnValidToChanged();
                this.OnPropertyChanged("ValidTo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _ValidTo;
        partial void OnValidToChanging(global::System.DateTimeOffset value);
        partial void OnValidToChanged();
        /// <summary>
        /// There are no comments for Property PayrollFixedCompensationPlan in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PayrollFixedCompensationPlan")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.PayrollFixedCompensationPlan> PayrollFixedCompensationPlan
        {
            get
            {
                return this._PayrollFixedCompensationPlan;
            }
            set
            {
                this.OnPayrollFixedCompensationPlanChanging(value);
                this._PayrollFixedCompensationPlan = value;
                this.OnPayrollFixedCompensationPlanChanged();
                this.OnPropertyChanged("PayrollFixedCompensationPlan");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.PayrollFixedCompensationPlan> _PayrollFixedCompensationPlan = new global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.PayrollFixedCompensationPlan>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnPayrollFixedCompensationPlanChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Microsoft.Dynamics.DataEntities.PayrollFixedCompensationPlan> value);
        partial void OnPayrollFixedCompensationPlanChanged();
        /// <summary>
        /// There are no comments for Property JobDetail in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("JobDetail")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "JobDetail is required.")]
        public virtual global::Microsoft.Dynamics.DataEntities.JobDetail JobDetail
        {
            get
            {
                return this._JobDetail;
            }
            set
            {
                this.OnJobDetailChanging(value);
                this._JobDetail = value;
                this.OnJobDetailChanged();
                this.OnPropertyChanged("JobDetail");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.JobDetail _JobDetail;
        partial void OnJobDetailChanging(global::Microsoft.Dynamics.DataEntities.JobDetail value);
        partial void OnJobDetailChanged();
        /// <summary>
        /// There are no comments for Property PayrollPosition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PayrollPosition")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "PayrollPosition is required.")]
        public virtual global::Microsoft.Dynamics.DataEntities.PayrollPosition PayrollPosition
        {
            get
            {
                return this._PayrollPosition;
            }
            set
            {
                this.OnPayrollPositionChanging(value);
                this._PayrollPosition = value;
                this.OnPayrollPositionChanged();
                this.OnPropertyChanged("PayrollPosition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Dynamics.DataEntities.PayrollPosition _PayrollPosition;
        partial void OnPayrollPositionChanging(global::Microsoft.Dynamics.DataEntities.PayrollPosition value);
        partial void OnPayrollPositionChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
