//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for PremiumEarningPolicyRuleTypeSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("PremiumEarningPolicyRuleTypeSingle")]
    public partial class PremiumEarningPolicyRuleTypeSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<PremiumEarningPolicyRuleType>
    {
        /// <summary>
        /// Initialize a new PremiumEarningPolicyRuleTypeSingle object.
        /// </summary>
        public PremiumEarningPolicyRuleTypeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PremiumEarningPolicyRuleTypeSingle object.
        /// </summary>
        public PremiumEarningPolicyRuleTypeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new PremiumEarningPolicyRuleTypeSingle object.
        /// </summary>
        public PremiumEarningPolicyRuleTypeSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<PremiumEarningPolicyRuleType> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for PremiumEarningPolicyRuleType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// RuleName
    /// QueryName
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("RuleName", "QueryName")]
    [global::Microsoft.OData.Client.EntitySet("PremiumEarningPolicyRuleTypes")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("PremiumEarningPolicyRuleType")]
    public partial class PremiumEarningPolicyRuleType : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new PremiumEarningPolicyRuleType object.
        /// </summary>
        /// <param name="ruleName">Initial value of RuleName.</param>
        /// <param name="queryName">Initial value of QueryName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static PremiumEarningPolicyRuleType CreatePremiumEarningPolicyRuleType(string ruleName, string queryName)
        {
            PremiumEarningPolicyRuleType premiumEarningPolicyRuleType = new PremiumEarningPolicyRuleType();
            premiumEarningPolicyRuleType.RuleName = ruleName;
            premiumEarningPolicyRuleType.QueryName = queryName;
            return premiumEarningPolicyRuleType;
        }
        /// <summary>
        /// There are no comments for Property RuleName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RuleName")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "RuleName is required.")]
        public virtual string RuleName
        {
            get
            {
                return this._RuleName;
            }
            set
            {
                this.OnRuleNameChanging(value);
                this._RuleName = value;
                this.OnRuleNameChanged();
                this.OnPropertyChanged("RuleName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RuleName;
        partial void OnRuleNameChanging(string value);
        partial void OnRuleNameChanged();
        /// <summary>
        /// There are no comments for Property QueryName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("QueryName")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "QueryName is required.")]
        public virtual string QueryName
        {
            get
            {
                return this._QueryName;
            }
            set
            {
                this.OnQueryNameChanging(value);
                this._QueryName = value;
                this.OnQueryNameChanged();
                this.OnPropertyChanged("QueryName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _QueryName;
        partial void OnQueryNameChanging(string value);
        partial void OnQueryNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Description")]
        public virtual string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
