//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for ProjectControlSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ProjectControlSingle")]
    public partial class ProjectControlSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<ProjectControl>
    {
        /// <summary>
        /// Initialize a new ProjectControlSingle object.
        /// </summary>
        public ProjectControlSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ProjectControlSingle object.
        /// </summary>
        public ProjectControlSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ProjectControlSingle object.
        /// </summary>
        public ProjectControlSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<ProjectControl> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for ProjectControl in the schema.
    /// </summary>
    /// <KeyProperties>
    /// DataAreaId
    /// CostTemplateId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("dataAreaId", "CostTemplateId")]
    [global::Microsoft.OData.Client.EntitySet("ProjectControls")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("ProjectControl")]
    public partial class ProjectControl : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ProjectControl object.
        /// </summary>
        /// <param name="dataAreaId">Initial value of DataAreaId.</param>
        /// <param name="costTemplateId">Initial value of CostTemplateId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static ProjectControl CreateProjectControl(string dataAreaId, string costTemplateId)
        {
            ProjectControl projectControl = new ProjectControl();
            projectControl.DataAreaId = dataAreaId;
            projectControl.CostTemplateId = costTemplateId;
            return projectControl;
        }
        /// <summary>
        /// There are no comments for Property DataAreaId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("dataAreaId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "DataAreaId is required.")]
        public virtual string DataAreaId
        {
            get
            {
                return this._DataAreaId;
            }
            set
            {
                this.OnDataAreaIdChanging(value);
                this._DataAreaId = value;
                this.OnDataAreaIdChanged();
                this.OnPropertyChanged("dataAreaId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DataAreaId;
        partial void OnDataAreaIdChanging(string value);
        partial void OnDataAreaIdChanged();
        /// <summary>
        /// There are no comments for Property CostTemplateId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CostTemplateId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "CostTemplateId is required.")]
        public virtual string CostTemplateId
        {
            get
            {
                return this._CostTemplateId;
            }
            set
            {
                this.OnCostTemplateIdChanging(value);
                this._CostTemplateId = value;
                this.OnCostTemplateIdChanged();
                this.OnPropertyChanged("CostTemplateId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _CostTemplateId;
        partial void OnCostTemplateIdChanging(string value);
        partial void OnCostTemplateIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property CompletionBasedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CompletionBasedOn")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.AmountUnit> CompletionBasedOn
        {
            get
            {
                return this._CompletionBasedOn;
            }
            set
            {
                this.OnCompletionBasedOnChanging(value);
                this._CompletionBasedOn = value;
                this.OnCompletionBasedOnChanged();
                this.OnPropertyChanged("CompletionBasedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.AmountUnit> _CompletionBasedOn;
        partial void OnCompletionBasedOnChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.AmountUnit> value);
        partial void OnCompletionBasedOnChanged();
        /// <summary>
        /// There are no comments for Property CompletionMethod in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CompletionMethod")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.ProjAutoManual> CompletionMethod
        {
            get
            {
                return this._CompletionMethod;
            }
            set
            {
                this.OnCompletionMethodChanging(value);
                this._CompletionMethod = value;
                this.OnCompletionMethodChanged();
                this.OnPropertyChanged("CompletionMethod");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.ProjAutoManual> _CompletionMethod;
        partial void OnCompletionMethodChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.ProjAutoManual> value);
        partial void OnCompletionMethodChanged();
        /// <summary>
        /// There are no comments for Property ItemCostLineId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ItemCostLineId")]
        public virtual string ItemCostLineId
        {
            get
            {
                return this._ItemCostLineId;
            }
            set
            {
                this.OnItemCostLineIdChanging(value);
                this._ItemCostLineId = value;
                this.OnItemCostLineIdChanged();
                this.OnPropertyChanged("ItemCostLineId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ItemCostLineId;
        partial void OnItemCostLineIdChanging(string value);
        partial void OnItemCostLineIdChanged();
        /// <summary>
        /// There are no comments for Property ExpenseCostLineId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ExpenseCostLineId")]
        public virtual string ExpenseCostLineId
        {
            get
            {
                return this._ExpenseCostLineId;
            }
            set
            {
                this.OnExpenseCostLineIdChanging(value);
                this._ExpenseCostLineId = value;
                this.OnExpenseCostLineIdChanged();
                this.OnPropertyChanged("ExpenseCostLineId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ExpenseCostLineId;
        partial void OnExpenseCostLineIdChanging(string value);
        partial void OnExpenseCostLineIdChanged();
        /// <summary>
        /// There are no comments for Property HourCostLineId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("HourCostLineId")]
        public virtual string HourCostLineId
        {
            get
            {
                return this._HourCostLineId;
            }
            set
            {
                this.OnHourCostLineIdChanging(value);
                this._HourCostLineId = value;
                this.OnHourCostLineIdChanged();
                this.OnPropertyChanged("HourCostLineId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _HourCostLineId;
        partial void OnHourCostLineIdChanging(string value);
        partial void OnHourCostLineIdChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
