//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for PropertyTypeApplicabilitySetupSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("PropertyTypeApplicabilitySetupSingle")]
    public partial class PropertyTypeApplicabilitySetupSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<PropertyTypeApplicabilitySetup>
    {
        /// <summary>
        /// Initialize a new PropertyTypeApplicabilitySetupSingle object.
        /// </summary>
        public PropertyTypeApplicabilitySetupSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PropertyTypeApplicabilitySetupSingle object.
        /// </summary>
        public PropertyTypeApplicabilitySetupSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new PropertyTypeApplicabilitySetupSingle object.
        /// </summary>
        public PropertyTypeApplicabilitySetupSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<PropertyTypeApplicabilitySetup> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for PropertyTypeApplicabilitySetup in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PropertyType
    /// TableName
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("PropertyType", "TableName")]
    [global::Microsoft.OData.Client.EntitySet("PropertyTypeApplicabilitySetups")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("PropertyTypeApplicabilitySetup")]
    public partial class PropertyTypeApplicabilitySetup : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new PropertyTypeApplicabilitySetup object.
        /// </summary>
        /// <param name="propertyType">Initial value of PropertyType.</param>
        /// <param name="tableName">Initial value of TableName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static PropertyTypeApplicabilitySetup CreatePropertyTypeApplicabilitySetup(string propertyType, string tableName)
        {
            PropertyTypeApplicabilitySetup propertyTypeApplicabilitySetup = new PropertyTypeApplicabilitySetup();
            propertyTypeApplicabilitySetup.PropertyType = propertyType;
            propertyTypeApplicabilitySetup.TableName = tableName;
            return propertyTypeApplicabilitySetup;
        }
        /// <summary>
        /// There are no comments for Property PropertyType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PropertyType")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "PropertyType is required.")]
        public virtual string PropertyType
        {
            get
            {
                return this._PropertyType;
            }
            set
            {
                this.OnPropertyTypeChanging(value);
                this._PropertyType = value;
                this.OnPropertyTypeChanged();
                this.OnPropertyChanged("PropertyType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PropertyType;
        partial void OnPropertyTypeChanging(string value);
        partial void OnPropertyTypeChanged();
        /// <summary>
        /// There are no comments for Property TableName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TableName")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "TableName is required.")]
        public virtual string TableName
        {
            get
            {
                return this._TableName;
            }
            set
            {
                this.OnTableNameChanging(value);
                this._TableName = value;
                this.OnTableNameChanged();
                this.OnPropertyChanged("TableName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TableName;
        partial void OnTableNameChanging(string value);
        partial void OnTableNameChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
