//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for RetailChannelType in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("RetailChannelType")]
    public enum RetailChannelType
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("RetailStore")]
        RetailStore = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("OnlineStore")]
        OnlineStore = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("OnlineMarketplace")]
        OnlineMarketplace = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("SharePointOnlineStore")]
        SharePointOnlineStore = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("MCRCallCenter")]
        MCRCallCenter = 4
    }
}
