//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for RetailLoyaltyProgramTranslationSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("RetailLoyaltyProgramTranslationSingle")]
    public partial class RetailLoyaltyProgramTranslationSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<RetailLoyaltyProgramTranslation>
    {
        /// <summary>
        /// Initialize a new RetailLoyaltyProgramTranslationSingle object.
        /// </summary>
        public RetailLoyaltyProgramTranslationSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new RetailLoyaltyProgramTranslationSingle object.
        /// </summary>
        public RetailLoyaltyProgramTranslationSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new RetailLoyaltyProgramTranslationSingle object.
        /// </summary>
        public RetailLoyaltyProgramTranslationSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<RetailLoyaltyProgramTranslation> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for RetailLoyaltyProgramTranslation in the schema.
    /// </summary>
    /// <KeyProperties>
    /// LanguageId
    /// LoyaltyProgramName
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("LanguageId", "LoyaltyProgramName")]
    [global::Microsoft.OData.Client.EntitySet("RetailLoyaltyProgramTranslations")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("RetailLoyaltyProgramTranslation")]
    public partial class RetailLoyaltyProgramTranslation : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RetailLoyaltyProgramTranslation object.
        /// </summary>
        /// <param name="languageId">Initial value of LanguageId.</param>
        /// <param name="loyaltyProgramName">Initial value of LoyaltyProgramName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static RetailLoyaltyProgramTranslation CreateRetailLoyaltyProgramTranslation(string languageId, string loyaltyProgramName)
        {
            RetailLoyaltyProgramTranslation retailLoyaltyProgramTranslation = new RetailLoyaltyProgramTranslation();
            retailLoyaltyProgramTranslation.LanguageId = languageId;
            retailLoyaltyProgramTranslation.LoyaltyProgramName = loyaltyProgramName;
            return retailLoyaltyProgramTranslation;
        }
        /// <summary>
        /// There are no comments for Property LanguageId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LanguageId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "LanguageId is required.")]
        public virtual string LanguageId
        {
            get
            {
                return this._LanguageId;
            }
            set
            {
                this.OnLanguageIdChanging(value);
                this._LanguageId = value;
                this.OnLanguageIdChanged();
                this.OnPropertyChanged("LanguageId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _LanguageId;
        partial void OnLanguageIdChanging(string value);
        partial void OnLanguageIdChanged();
        /// <summary>
        /// There are no comments for Property LoyaltyProgramName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LoyaltyProgramName")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "LoyaltyProgramName is required.")]
        public virtual string LoyaltyProgramName
        {
            get
            {
                return this._LoyaltyProgramName;
            }
            set
            {
                this.OnLoyaltyProgramNameChanging(value);
                this._LoyaltyProgramName = value;
                this.OnLoyaltyProgramNameChanged();
                this.OnPropertyChanged("LoyaltyProgramName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _LoyaltyProgramName;
        partial void OnLoyaltyProgramNameChanging(string value);
        partial void OnLoyaltyProgramNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Description")]
        public virtual string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
