//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for RetailInfocodeTransType in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("RetailInfocodeTransType")]
    public enum RetailInfocodeTransType
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Header")]
        Header = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Sales")]
        Sales = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Payment")]
        Payment = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("IncomeExpense")]
        IncomeExpense = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("NoSale")]
        NoSale = 4,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Affiliation")]
        Affiliation = 5,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Fiscal")]
        Fiscal = 6
    }
}
