//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for SalesOrderProcessingStatus in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("SalesOrderProcessingStatus")]
    public enum SalesOrderProcessingStatus
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Active")]
        Active = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Confirmed")]
        Confirmed = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Picked")]
        Picked = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("PartiallyDelivered")]
        PartiallyDelivered = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Delivered")]
        Delivered = 4,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Invoiced")]
        Invoiced = 5,
        [global::Microsoft.OData.Client.OriginalNameAttribute("PartiallyInvoiced")]
        PartiallyInvoiced = 6,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Canceled")]
        Canceled = 7
    }
}
