//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for SecurityDutyV2Single in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("SecurityDutyV2Single")]
    public partial class SecurityDutyV2Single : global::Microsoft.OData.Client.DataServiceQuerySingle<SecurityDutyV2>
    {
        /// <summary>
        /// Initialize a new SecurityDutyV2Single object.
        /// </summary>
        public SecurityDutyV2Single(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new SecurityDutyV2Single object.
        /// </summary>
        public SecurityDutyV2Single(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new SecurityDutyV2Single object.
        /// </summary>
        public SecurityDutyV2Single(global::Microsoft.OData.Client.DataServiceQuerySingle<SecurityDutyV2> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for SecurityDutyV2 in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SecurityRoleIdentifier
    /// SecurityDutyIdentifier
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("SecurityRoleIdentifier", "SecurityDutyIdentifier")]
    [global::Microsoft.OData.Client.EntitySet("SecurityDutiesV2")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("SecurityDutyV2")]
    public partial class SecurityDutyV2 : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SecurityDutyV2 object.
        /// </summary>
        /// <param name="securityRoleIdentifier">Initial value of SecurityRoleIdentifier.</param>
        /// <param name="securityDutyIdentifier">Initial value of SecurityDutyIdentifier.</param>
        /// <param name="securityPrivilege">Initial value of SecurityPrivilege.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static SecurityDutyV2 CreateSecurityDutyV2(string securityRoleIdentifier, string securityDutyIdentifier, long securityPrivilege)
        {
            SecurityDutyV2 securityDutyV2 = new SecurityDutyV2();
            securityDutyV2.SecurityRoleIdentifier = securityRoleIdentifier;
            securityDutyV2.SecurityDutyIdentifier = securityDutyIdentifier;
            securityDutyV2.SecurityPrivilege = securityPrivilege;
            return securityDutyV2;
        }
        /// <summary>
        /// There are no comments for Property SecurityRoleIdentifier in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SecurityRoleIdentifier")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "SecurityRoleIdentifier is required.")]
        public virtual string SecurityRoleIdentifier
        {
            get
            {
                return this._SecurityRoleIdentifier;
            }
            set
            {
                this.OnSecurityRoleIdentifierChanging(value);
                this._SecurityRoleIdentifier = value;
                this.OnSecurityRoleIdentifierChanged();
                this.OnPropertyChanged("SecurityRoleIdentifier");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SecurityRoleIdentifier;
        partial void OnSecurityRoleIdentifierChanging(string value);
        partial void OnSecurityRoleIdentifierChanged();
        /// <summary>
        /// There are no comments for Property SecurityDutyIdentifier in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SecurityDutyIdentifier")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "SecurityDutyIdentifier is required.")]
        public virtual string SecurityDutyIdentifier
        {
            get
            {
                return this._SecurityDutyIdentifier;
            }
            set
            {
                this.OnSecurityDutyIdentifierChanging(value);
                this._SecurityDutyIdentifier = value;
                this.OnSecurityDutyIdentifierChanged();
                this.OnPropertyChanged("SecurityDutyIdentifier");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SecurityDutyIdentifier;
        partial void OnSecurityDutyIdentifierChanging(string value);
        partial void OnSecurityDutyIdentifierChanged();
        /// <summary>
        /// There are no comments for Property SecurityDutyName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SecurityDutyName")]
        public virtual string SecurityDutyName
        {
            get
            {
                return this._SecurityDutyName;
            }
            set
            {
                this.OnSecurityDutyNameChanging(value);
                this._SecurityDutyName = value;
                this.OnSecurityDutyNameChanged();
                this.OnPropertyChanged("SecurityDutyName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SecurityDutyName;
        partial void OnSecurityDutyNameChanging(string value);
        partial void OnSecurityDutyNameChanged();
        /// <summary>
        /// There are no comments for Property SecurityPrivilegeIdentifier in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SecurityPrivilegeIdentifier")]
        public virtual string SecurityPrivilegeIdentifier
        {
            get
            {
                return this._SecurityPrivilegeIdentifier;
            }
            set
            {
                this.OnSecurityPrivilegeIdentifierChanging(value);
                this._SecurityPrivilegeIdentifier = value;
                this.OnSecurityPrivilegeIdentifierChanged();
                this.OnPropertyChanged("SecurityPrivilegeIdentifier");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SecurityPrivilegeIdentifier;
        partial void OnSecurityPrivilegeIdentifierChanging(string value);
        partial void OnSecurityPrivilegeIdentifierChanged();
        /// <summary>
        /// There are no comments for Property SecurityPrivilegeName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SecurityPrivilegeName")]
        public virtual string SecurityPrivilegeName
        {
            get
            {
                return this._SecurityPrivilegeName;
            }
            set
            {
                this.OnSecurityPrivilegeNameChanging(value);
                this._SecurityPrivilegeName = value;
                this.OnSecurityPrivilegeNameChanged();
                this.OnPropertyChanged("SecurityPrivilegeName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SecurityPrivilegeName;
        partial void OnSecurityPrivilegeNameChanging(string value);
        partial void OnSecurityPrivilegeNameChanged();
        /// <summary>
        /// There are no comments for Property SecurityPrivilege in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SecurityPrivilege")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "SecurityPrivilege is required.")]
        public virtual long SecurityPrivilege
        {
            get
            {
                return this._SecurityPrivilege;
            }
            set
            {
                this.OnSecurityPrivilegeChanging(value);
                this._SecurityPrivilege = value;
                this.OnSecurityPrivilegeChanged();
                this.OnPropertyChanged("SecurityPrivilege");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private long _SecurityPrivilege;
        partial void OnSecurityPrivilegeChanging(long value);
        partial void OnSecurityPrivilegeChanged();
        /// <summary>
        /// There are no comments for Property SecurityRoleName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SecurityRoleName")]
        public virtual string SecurityRoleName
        {
            get
            {
                return this._SecurityRoleName;
            }
            set
            {
                this.OnSecurityRoleNameChanging(value);
                this._SecurityRoleName = value;
                this.OnSecurityRoleNameChanged();
                this.OnPropertyChanged("SecurityRoleName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _SecurityRoleName;
        partial void OnSecurityRoleNameChanging(string value);
        partial void OnSecurityRoleNameChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
