//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for ServiceSubscriptionGroupSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ServiceSubscriptionGroupSingle")]
    public partial class ServiceSubscriptionGroupSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<ServiceSubscriptionGroup>
    {
        /// <summary>
        /// Initialize a new ServiceSubscriptionGroupSingle object.
        /// </summary>
        public ServiceSubscriptionGroupSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ServiceSubscriptionGroupSingle object.
        /// </summary>
        public ServiceSubscriptionGroupSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ServiceSubscriptionGroupSingle object.
        /// </summary>
        public ServiceSubscriptionGroupSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<ServiceSubscriptionGroup> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for ServiceSubscriptionGroup in the schema.
    /// </summary>
    /// <KeyProperties>
    /// DataAreaId
    /// GroupId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("dataAreaId", "GroupId")]
    [global::Microsoft.OData.Client.EntitySet("ServiceSubscriptionGroups")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("ServiceSubscriptionGroup")]
    public partial class ServiceSubscriptionGroup : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ServiceSubscriptionGroup object.
        /// </summary>
        /// <param name="dataAreaId">Initial value of DataAreaId.</param>
        /// <param name="groupId">Initial value of GroupId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static ServiceSubscriptionGroup CreateServiceSubscriptionGroup(string dataAreaId, string groupId)
        {
            ServiceSubscriptionGroup serviceSubscriptionGroup = new ServiceSubscriptionGroup();
            serviceSubscriptionGroup.DataAreaId = dataAreaId;
            serviceSubscriptionGroup.GroupId = groupId;
            return serviceSubscriptionGroup;
        }
        /// <summary>
        /// There are no comments for Property DataAreaId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("dataAreaId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "DataAreaId is required.")]
        public virtual string DataAreaId
        {
            get
            {
                return this._DataAreaId;
            }
            set
            {
                this.OnDataAreaIdChanging(value);
                this._DataAreaId = value;
                this.OnDataAreaIdChanged();
                this.OnPropertyChanged("dataAreaId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DataAreaId;
        partial void OnDataAreaIdChanging(string value);
        partial void OnDataAreaIdChanged();
        /// <summary>
        /// There are no comments for Property GroupId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("GroupId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "GroupId is required.")]
        public virtual string GroupId
        {
            get
            {
                return this._GroupId;
            }
            set
            {
                this.OnGroupIdChanging(value);
                this._GroupId = value;
                this.OnGroupIdChanged();
                this.OnPropertyChanged("GroupId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _GroupId;
        partial void OnGroupIdChanging(string value);
        partial void OnGroupIdChanged();
        /// <summary>
        /// There are no comments for Property ServiceSubscriptionNumberSequenceCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ServiceSubscriptionNumberSequenceCode")]
        public virtual string ServiceSubscriptionNumberSequenceCode
        {
            get
            {
                return this._ServiceSubscriptionNumberSequenceCode;
            }
            set
            {
                this.OnServiceSubscriptionNumberSequenceCodeChanging(value);
                this._ServiceSubscriptionNumberSequenceCode = value;
                this.OnServiceSubscriptionNumberSequenceCodeChanged();
                this.OnPropertyChanged("ServiceSubscriptionNumberSequenceCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ServiceSubscriptionNumberSequenceCode;
        partial void OnServiceSubscriptionNumberSequenceCodeChanging(string value);
        partial void OnServiceSubscriptionNumberSequenceCodeChanged();
        /// <summary>
        /// There are no comments for Property InvoiceFrequencyPeriodTypeCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("InvoiceFrequencyPeriodTypeCode")]
        public virtual string InvoiceFrequencyPeriodTypeCode
        {
            get
            {
                return this._InvoiceFrequencyPeriodTypeCode;
            }
            set
            {
                this.OnInvoiceFrequencyPeriodTypeCodeChanging(value);
                this._InvoiceFrequencyPeriodTypeCode = value;
                this.OnInvoiceFrequencyPeriodTypeCodeChanged();
                this.OnPropertyChanged("InvoiceFrequencyPeriodTypeCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _InvoiceFrequencyPeriodTypeCode;
        partial void OnInvoiceFrequencyPeriodTypeCodeChanging(string value);
        partial void OnInvoiceFrequencyPeriodTypeCodeChanged();
        /// <summary>
        /// There are no comments for Property AccrualFrequencyPeriodTypeCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AccrualFrequencyPeriodTypeCode")]
        public virtual string AccrualFrequencyPeriodTypeCode
        {
            get
            {
                return this._AccrualFrequencyPeriodTypeCode;
            }
            set
            {
                this.OnAccrualFrequencyPeriodTypeCodeChanging(value);
                this._AccrualFrequencyPeriodTypeCode = value;
                this.OnAccrualFrequencyPeriodTypeCodeChanged();
                this.OnPropertyChanged("AccrualFrequencyPeriodTypeCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _AccrualFrequencyPeriodTypeCode;
        partial void OnAccrualFrequencyPeriodTypeCodeChanging(string value);
        partial void OnAccrualFrequencyPeriodTypeCodeChanged();
        /// <summary>
        /// There are no comments for Property IsRevenueAccrued in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("IsRevenueAccrued")]
        public virtual global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> IsRevenueAccrued
        {
            get
            {
                return this._IsRevenueAccrued;
            }
            set
            {
                this.OnIsRevenueAccruedChanging(value);
                this._IsRevenueAccrued = value;
                this.OnIsRevenueAccruedChanged();
                this.OnPropertyChanged("IsRevenueAccrued");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> _IsRevenueAccrued;
        partial void OnIsRevenueAccruedChanging(global::System.Nullable<global::Microsoft.Dynamics.DataEntities.NoYes> value);
        partial void OnIsRevenueAccruedChanged();
        /// <summary>
        /// There are no comments for Property GroupName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("GroupName")]
        public virtual string GroupName
        {
            get
            {
                return this._GroupName;
            }
            set
            {
                this.OnGroupNameChanging(value);
                this._GroupName = value;
                this.OnGroupNameChanged();
                this.OnPropertyChanged("GroupName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _GroupName;
        partial void OnGroupNameChanging(string value);
        partial void OnGroupNameChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
