//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for SubBillRevenueSplitAllocationMethod in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("SubBillRevenueSplitAllocationMethod")]
    public enum SubBillRevenueSplitAllocationMethod
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("VariableAmount")]
        VariableAmount = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Percentage")]
        Percentage = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("EqualAmount")]
        EqualAmount = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("ZeroAmount")]
        ZeroAmount = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("ZeroParentAmount")]
        ZeroParentAmount = 4
    }
}
