//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for Tax1099Type in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Tax1099Type")]
    public enum Tax1099Type
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("F1099DIV")]
        F1099DIV = 7,
        [global::Microsoft.OData.Client.OriginalNameAttribute("F1099INT")]
        F1099INT = 10,
        [global::Microsoft.OData.Client.OriginalNameAttribute("F1099MISC")]
        F1099MISC = 12,
        [global::Microsoft.OData.Client.OriginalNameAttribute("F1099OID")]
        F1099OID = 27,
        [global::Microsoft.OData.Client.OriginalNameAttribute("F1099G")]
        F1099G = 13,
        [global::Microsoft.OData.Client.OriginalNameAttribute("F1099S")]
        F1099S = 14,
        [global::Microsoft.OData.Client.OriginalNameAttribute("F1099NEC")]
        F1099NEC = 29
    }
}
