//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 11/27/2022 9:27:22 PM
namespace Microsoft.Dynamics.DataEntities
{
    /// <summary>
    /// There are no comments for VendorRebateAgreementLineSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("VendorRebateAgreementLineSingle")]
    public partial class VendorRebateAgreementLineSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<VendorRebateAgreementLine>
    {
        /// <summary>
        /// Initialize a new VendorRebateAgreementLineSingle object.
        /// </summary>
        public VendorRebateAgreementLineSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new VendorRebateAgreementLineSingle object.
        /// </summary>
        public VendorRebateAgreementLineSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new VendorRebateAgreementLineSingle object.
        /// </summary>
        public VendorRebateAgreementLineSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<VendorRebateAgreementLine> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for VendorRebateAgreementLine in the schema.
    /// </summary>
    /// <KeyProperties>
    /// DataAreaId
    /// RebateAgreementId
    /// LineNumber
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("dataAreaId", "RebateAgreementId", "LineNumber")]
    [global::Microsoft.OData.Client.EntitySet("VendorRebateAgreementLines")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("VendorRebateAgreementLine")]
    public partial class VendorRebateAgreementLine : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new VendorRebateAgreementLine object.
        /// </summary>
        /// <param name="dataAreaId">Initial value of DataAreaId.</param>
        /// <param name="rebateAgreementId">Initial value of RebateAgreementId.</param>
        /// <param name="lineNumber">Initial value of LineNumber.</param>
        /// <param name="fromNetPurchaseAmount">Initial value of FromNetPurchaseAmount.</param>
        /// <param name="fromGrossPurchaseAmount">Initial value of FromGrossPurchaseAmount.</param>
        /// <param name="fixedRebateAmount">Initial value of FixedRebateAmount.</param>
        /// <param name="toNetPurchaseAmount">Initial value of ToNetPurchaseAmount.</param>
        /// <param name="rebatePercentage">Initial value of RebatePercentage.</param>
        /// <param name="rebateAmountPerProductUnitSold">Initial value of RebateAmountPerProductUnitSold.</param>
        /// <param name="toGrossPurchaseAmount">Initial value of ToGrossPurchaseAmount.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static VendorRebateAgreementLine CreateVendorRebateAgreementLine(string dataAreaId, 
                    string rebateAgreementId, 
                    decimal lineNumber, 
                    decimal fromNetPurchaseAmount, 
                    decimal fromGrossPurchaseAmount, 
                    decimal fixedRebateAmount, 
                    decimal toNetPurchaseAmount, 
                    decimal rebatePercentage, 
                    decimal rebateAmountPerProductUnitSold, 
                    decimal toGrossPurchaseAmount)
        {
            VendorRebateAgreementLine vendorRebateAgreementLine = new VendorRebateAgreementLine();
            vendorRebateAgreementLine.DataAreaId = dataAreaId;
            vendorRebateAgreementLine.RebateAgreementId = rebateAgreementId;
            vendorRebateAgreementLine.LineNumber = lineNumber;
            vendorRebateAgreementLine.FromNetPurchaseAmount = fromNetPurchaseAmount;
            vendorRebateAgreementLine.FromGrossPurchaseAmount = fromGrossPurchaseAmount;
            vendorRebateAgreementLine.FixedRebateAmount = fixedRebateAmount;
            vendorRebateAgreementLine.ToNetPurchaseAmount = toNetPurchaseAmount;
            vendorRebateAgreementLine.RebatePercentage = rebatePercentage;
            vendorRebateAgreementLine.RebateAmountPerProductUnitSold = rebateAmountPerProductUnitSold;
            vendorRebateAgreementLine.ToGrossPurchaseAmount = toGrossPurchaseAmount;
            return vendorRebateAgreementLine;
        }
        /// <summary>
        /// There are no comments for Property DataAreaId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("dataAreaId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "DataAreaId is required.")]
        public virtual string DataAreaId
        {
            get
            {
                return this._DataAreaId;
            }
            set
            {
                this.OnDataAreaIdChanging(value);
                this._DataAreaId = value;
                this.OnDataAreaIdChanged();
                this.OnPropertyChanged("dataAreaId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DataAreaId;
        partial void OnDataAreaIdChanging(string value);
        partial void OnDataAreaIdChanged();
        /// <summary>
        /// There are no comments for Property RebateAgreementId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RebateAgreementId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "RebateAgreementId is required.")]
        public virtual string RebateAgreementId
        {
            get
            {
                return this._RebateAgreementId;
            }
            set
            {
                this.OnRebateAgreementIdChanging(value);
                this._RebateAgreementId = value;
                this.OnRebateAgreementIdChanged();
                this.OnPropertyChanged("RebateAgreementId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RebateAgreementId;
        partial void OnRebateAgreementIdChanging(string value);
        partial void OnRebateAgreementIdChanged();
        /// <summary>
        /// There are no comments for Property LineNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LineNumber")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "LineNumber is required.")]
        public virtual decimal LineNumber
        {
            get
            {
                return this._LineNumber;
            }
            set
            {
                this.OnLineNumberChanging(value);
                this._LineNumber = value;
                this.OnLineNumberChanged();
                this.OnPropertyChanged("LineNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _LineNumber;
        partial void OnLineNumberChanging(decimal value);
        partial void OnLineNumberChanged();
        /// <summary>
        /// There are no comments for Property VendorAccountNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("VendorAccountNumber")]
        public virtual string VendorAccountNumber
        {
            get
            {
                return this._VendorAccountNumber;
            }
            set
            {
                this.OnVendorAccountNumberChanging(value);
                this._VendorAccountNumber = value;
                this.OnVendorAccountNumberChanged();
                this.OnPropertyChanged("VendorAccountNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _VendorAccountNumber;
        partial void OnVendorAccountNumberChanging(string value);
        partial void OnVendorAccountNumberChanged();
        /// <summary>
        /// There are no comments for Property FromNetPurchaseAmount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FromNetPurchaseAmount")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "FromNetPurchaseAmount is required.")]
        public virtual decimal FromNetPurchaseAmount
        {
            get
            {
                return this._FromNetPurchaseAmount;
            }
            set
            {
                this.OnFromNetPurchaseAmountChanging(value);
                this._FromNetPurchaseAmount = value;
                this.OnFromNetPurchaseAmountChanged();
                this.OnPropertyChanged("FromNetPurchaseAmount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _FromNetPurchaseAmount;
        partial void OnFromNetPurchaseAmountChanging(decimal value);
        partial void OnFromNetPurchaseAmountChanged();
        /// <summary>
        /// There are no comments for Property FromGrossPurchaseAmount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FromGrossPurchaseAmount")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "FromGrossPurchaseAmount is required.")]
        public virtual decimal FromGrossPurchaseAmount
        {
            get
            {
                return this._FromGrossPurchaseAmount;
            }
            set
            {
                this.OnFromGrossPurchaseAmountChanging(value);
                this._FromGrossPurchaseAmount = value;
                this.OnFromGrossPurchaseAmountChanged();
                this.OnPropertyChanged("FromGrossPurchaseAmount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _FromGrossPurchaseAmount;
        partial void OnFromGrossPurchaseAmountChanging(decimal value);
        partial void OnFromGrossPurchaseAmountChanged();
        /// <summary>
        /// There are no comments for Property CurrencyCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CurrencyCode")]
        public virtual string CurrencyCode
        {
            get
            {
                return this._CurrencyCode;
            }
            set
            {
                this.OnCurrencyCodeChanging(value);
                this._CurrencyCode = value;
                this.OnCurrencyCodeChanged();
                this.OnPropertyChanged("CurrencyCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _CurrencyCode;
        partial void OnCurrencyCodeChanging(string value);
        partial void OnCurrencyCodeChanged();
        /// <summary>
        /// There are no comments for Property FixedRebateAmount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FixedRebateAmount")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "FixedRebateAmount is required.")]
        public virtual decimal FixedRebateAmount
        {
            get
            {
                return this._FixedRebateAmount;
            }
            set
            {
                this.OnFixedRebateAmountChanging(value);
                this._FixedRebateAmount = value;
                this.OnFixedRebateAmountChanged();
                this.OnPropertyChanged("FixedRebateAmount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _FixedRebateAmount;
        partial void OnFixedRebateAmountChanging(decimal value);
        partial void OnFixedRebateAmountChanged();
        /// <summary>
        /// There are no comments for Property ToNetPurchaseAmount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ToNetPurchaseAmount")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ToNetPurchaseAmount is required.")]
        public virtual decimal ToNetPurchaseAmount
        {
            get
            {
                return this._ToNetPurchaseAmount;
            }
            set
            {
                this.OnToNetPurchaseAmountChanging(value);
                this._ToNetPurchaseAmount = value;
                this.OnToNetPurchaseAmountChanged();
                this.OnPropertyChanged("ToNetPurchaseAmount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _ToNetPurchaseAmount;
        partial void OnToNetPurchaseAmountChanging(decimal value);
        partial void OnToNetPurchaseAmountChanged();
        /// <summary>
        /// There are no comments for Property RebatePercentage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RebatePercentage")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "RebatePercentage is required.")]
        public virtual decimal RebatePercentage
        {
            get
            {
                return this._RebatePercentage;
            }
            set
            {
                this.OnRebatePercentageChanging(value);
                this._RebatePercentage = value;
                this.OnRebatePercentageChanged();
                this.OnPropertyChanged("RebatePercentage");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _RebatePercentage;
        partial void OnRebatePercentageChanging(decimal value);
        partial void OnRebatePercentageChanged();
        /// <summary>
        /// There are no comments for Property RebateAmountPerProductUnitSold in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RebateAmountPerProductUnitSold")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "RebateAmountPerProductUnitSold is required.")]
        public virtual decimal RebateAmountPerProductUnitSold
        {
            get
            {
                return this._RebateAmountPerProductUnitSold;
            }
            set
            {
                this.OnRebateAmountPerProductUnitSoldChanging(value);
                this._RebateAmountPerProductUnitSold = value;
                this.OnRebateAmountPerProductUnitSoldChanged();
                this.OnPropertyChanged("RebateAmountPerProductUnitSold");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _RebateAmountPerProductUnitSold;
        partial void OnRebateAmountPerProductUnitSoldChanging(decimal value);
        partial void OnRebateAmountPerProductUnitSoldChanged();
        /// <summary>
        /// There are no comments for Property ToGrossPurchaseAmount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ToGrossPurchaseAmount")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ToGrossPurchaseAmount is required.")]
        public virtual decimal ToGrossPurchaseAmount
        {
            get
            {
                return this._ToGrossPurchaseAmount;
            }
            set
            {
                this.OnToGrossPurchaseAmountChanging(value);
                this._ToGrossPurchaseAmount = value;
                this.OnToGrossPurchaseAmountChanged();
                this.OnPropertyChanged("ToGrossPurchaseAmount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _ToGrossPurchaseAmount;
        partial void OnToGrossPurchaseAmountChanging(decimal value);
        partial void OnToGrossPurchaseAmountChanged();
        /// <summary>
        /// There are no comments for Property UnitSymbol in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("UnitSymbol")]
        public virtual string UnitSymbol
        {
            get
            {
                return this._UnitSymbol;
            }
            set
            {
                this.OnUnitSymbolChanging(value);
                this._UnitSymbol = value;
                this.OnUnitSymbolChanged();
                this.OnPropertyChanged("UnitSymbol");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _UnitSymbol;
        partial void OnUnitSymbolChanging(string value);
        partial void OnUnitSymbolChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
